### ISSUE TITLE
Ruby 2.3 support

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3479]
Here's the living checklist of changes needed to support Ruby 2.3.

These changes will go on the 2.3 branch at https://github.com/jruby/jruby/tree/ruby-2.3 and then we will merge to master when we're ready to release 2.3 support in JRuby 9.1.0.0.

_Pull requests should be made against the `ruby-2.3` branch please!_

This list is currently based on https://github.com/ruby/ruby/blob/v2_3_0_preview2/NEWS.

Language changes
--------------------------

* frozen-string-literal pragma:
  - [x] new pragma, frozen-string-literal has been experimentally introduced. (https://bugs.ruby-lang.org/issues/8976)
  - [x] besides, --enable/--disable=frozen-string-literal options also have been introduced. (https://bugs.ruby-lang.org/issues/8976)
  - [x] command line options --debug or --debug=frozen-string-literal enable additional debugging mode which shows created location with at frozen object error (RuntimeError). (https://bugs.ruby-lang.org/issues/11725)

* safe navigation operator:
  - [x] new method call syntax, `object&.foo', method #foo is called on `object' if it is not nil.
    this is similar to `try!' in Active Support, except:
    * method name is syntactically required
          obj.try! {} # valid
          obj&. {}    # syntax error
    * arguments are evaluated only if a call is made:
          obj.try!(:foo, bar())  # bar() is always evaluated
          obj&.foo(bar())        # bar() is conditionally evaluated
    * attribute assignment is valid
          obj&.attr += 1
    * (https://bugs.ruby-lang.org/issues/11537)

* indented here document:
  - [x] new string literal, here document starts with `<<~`. refer doc/syntax/literals.rdoc for more details. (https://bugs.ruby-lang.org/issues/9098)

* Additional parser changes
  - [x] `class Foo end` is no longer a syntax error (see tagged specs in 0304cc7).

- [ ] Changes in how super works for methods copied from parent to child. See https://bugs.ruby-lang.org/issues/3351 and https://github.com/rspec/rspec-mocks/issues/1042

Core classes updates (outstanding ones only)
-------------------------------------------------------------

* ARGF
  - [x] ARGF.read_nonblock supports `exception: false' like IO#read_nonblock.
    (https://bugs.ruby-lang.org/issues/11358)

* Array
  - [x] Array#bsearch_index (https://bugs.ruby-lang.org/issues/10730)
  - [x] Array#dig (https://bugs.ruby-lang.org/issues/11643) needs rubyspec update (see #3458)

* Enumerable
  - [x] Enumerable#grep_v is added as inverse version of Enumerable#grep.
    (https://bugs.ruby-lang.org/issues/11049)
  - [x] Enumerable#chunk_while (https://bugs.ruby-lang.org/issues/10769)

* File
  - [x] File.mkfifo (https://bugs.ruby-lang.org/issues/11536) (4a79bca)
  - [x] Add File::TMPFILE corresponding to O_TMPFILE (876445b)

* Hash
  - [x] Hash#fetch_values (https://bugs.ruby-lang.org/issues/10017)
  - [x] Hash#dig (https://bugs.ruby-lang.org/issues/11643) needs rubyspec update (see #3458)
  - [x] Hash#<=, Hash#<, Hash#>=, Hash#> (https://bugs.ruby-lang.org/issues/10984)
  - [x] Hash#to_proc (https://bugs.ruby-lang.org/issues/11653)

* IO
  - [ ] new mode flag File::SHARE_DELETE is available.
    this flag means to permit deleting opened file on Windows, but currently
    this affect only files opened as binary.  (https://bugs.ruby-lang.org/issues/11218)
  - [x] new option parameter `flags' is added.
    this parameter is bitwise-ORed to oflags generated by normal mode argument.
    (https://bugs.ruby-lang.org/issues/11253)

* Kernel
  - [x] Kernel#loop, when stopped by a StopIteration exception, returns
    what the enumerator has returned instead of nil. (https://bugs.ruby-lang.org/issues/11498)

* Module
  - [x] Module#deprecate_constant (https://bugs.ruby-lang.org/issues/11398)

* NameError
  - [x] NameError#receiver is added to take the receiver object. (https://bugs.ruby-lang.org/issues/10881) (Added in f7088b937ea524da9b153d4d7ca2f2723b74aa19)

* Numeric
  - [x] Numeric#positive? and Numeric#negative? are added, which return
    true when the receiver is positive and negative respectively.
    (https://bugs.ruby-lang.org/issues/11151)

* Proc
  - [x] Proc#call (and also #[], #===, #yield) are optimized.
    Backtrace doesn't show each methods (show block lines directly).
    - [x] TracePoint also ignore these calls. (https://bugs.ruby-lang.org/issues/11569)
    - [ ] Testing

* Queue (Thread::Queue)
  - [x] Queue#close is added to notice a termination. (https://bugs.ruby-lang.org/issues/10600) (Added in 253114392f98ade8c2dbb20cfdc643c74c6a842d)
  - [x] Benchmark modified Queue and SizedQueue implementations from 253114392f98ade8c2dbb20cfdc643c74c6a842d. (New impls contributed in #3553 based on blocking queues we used to use)
  - [x] Reconcile tests that do not seem correct (https://bugs.ruby-lang.org/issues/11822)

- [ ] Regexp/String: Updated Unicode version from 7.0.0 to 8.0.0
  - [ ] Ensure manual change in https://github.com/jruby/jcodings/commit/4bcfdc3719f22d087037f6d0a362ac004c820fe5#diff-63b6d8b6c8616d7df068493913a90413R136 is preserved during update

* String
  - [x] String#+@ and String#-@ are added to get mutable/frozen strings. (https://bugs.ruby-lang.org/issues/11782)
  - [x] String.new now accepts new option parameter `encoding'. (https://bugs.ruby-lang.org/issues/11785)

* Struct
  - [x] Struct#dig (https://bugs.ruby-lang.org/issues/11688)

* Thread
  - [x] Thread#name, Thread#name= are added to handle thread names (https://bugs.ruby-lang.org/issues/11251)

Core classes compatibility issues (excluding feature bug fixes)
-----------------------------------------------------------------------------------

* Array
  - [x] Array#select!, Array#keep_if, Array#reject!, and Array#delete_if
    no longer changes the receiver array instantly every time the
    block is called.  (https://bugs.ruby-lang.org/issues/10714)
  - [x] Array#flatten and Array#flatten! no longer try to call #to_ary
    method on elements beyond the given level.  (https://bugs.ruby-lang.org/issues/10748)
  - [x] Array#inspect doesn't raise error even if its content returns
    a string which is not compatible with Encoding.default_external
    as inspected result. (https://bugs.ruby-lang.org/issues/11801) 7f47946e08402fdb44aab01e7f475567d92e2c99

* Enumerable
  - [x] Enumerable#chunk and Enumerable#slice_before no longer takes the
    initial_state argument.  (https://bugs.ruby-lang.org/issues/10958)
    Use a local variable instead to maintain a state. #3490

* File::Stat
  - [ ] On Windows File::Stat#ino always returned 0, but now returns
    BY_HANDLE_FILE_INFORMATION.nFileIndexHigh/Low.

* Hash
  - [x] Hash#inspect doesn't raise error even if its content returns
    a string which is not compatible with Encoding.default_external
    as inspected result. (https://bugs.ruby-lang.org/issues/11801) 7f47946e08402fdb44aab01e7f475567d92e2c99

* IO
  - [x] IO#close doesn't raise when the IO object is closed.  (https://bugs.ruby-lang.org/issues/10718)
  - [x] IO#each_codepoint raises an exception at incomplete character
    before EOF when conversion takes place.  (https://bugs.ruby-lang.org/issues/11444) (866c248)

* Module
  - [x] Module#define_method and Object.define_singleton_method now
    require method body, Proc, Method, or a block, and raise
    ArgumentError if no block is given directly.  (https://bugs.ruby-lang.org/issues/11283)

* StringIO
  - [x] StringIO#set_encoding sets an internal encoding - String only affected when writeable (https://bugs.ruby-lang.org/issues/11827)

* pack/unpack (Array/String)
  - [ ] j and J directives for pointer width integer type.  (https://bugs.ruby-lang.org/issues/11215)

Stdlib updates (outstanding ones only)
---------------------------------------------------

_Only items relevant to JRuby_

- [x] Update .rb parts of stdlib to 2.3 (delay until 2.3.0 final, probably) 66570f070229525f1c1b37fc4eb6f51c0fc96dec
* [ ] Bundle did_you_mean gem #3480

* Socket
  - [x] Socket#connect_nonblock, Socket#accept_nonblock,
    TCPServer#accept_nonblock, UNIXServer#accept_nonblock,
    BasicSocket#recv_nonblock, BasicSocket#recvmsg_nonblock,
    BasicSocket#sendmsg_nonblock all support `exception: false` to return
    :wait_readable or :wait_writable symbols instead of raising
    IO::WaitReadable or IO::WaitWritable exceptions (b27a2b0c009e814982910520df74de8300f0b033)
  - [x] BasicSocket#recv and BasicSocket#recv_nonblock allow an output
    String buffer argument like IO#read and IO#read_nonblock to reduce
    GC overhead

* OpenSSL
  - [x] OpenSSL::SSL::SSLSocket#accept_nonblock and
    OpenSSL::SSL::SSLSocket#connect_nonblock supports `exception: false`.
  - [x] update OpenSSL's .rb parts to match changes in 2.3
  - [x] test & update jruby-openssl to be **>= 0.9.13** (to incorporate above updates)

* Pathname
  - [x] Pathname#descend and Pathname#ascend supported blockless form.
    (https://bugs.ruby-lang.org/issues/11052)

* io/wait
  - [x] IO#wait_readable no longer checks FIONREAD, it may be used for
    non-bytestream IO such as listen sockets. (975dcc7 and 64638d0)

* timeout
  - [x] Object#timeout is now warned as deprecated when called. (a042a396bbe232efc78accbbfc66192c3229be17)

Stdlib compatibility issues (excluding feature bug fixes)
-------------------------------------------------------------------------

_Only items relevant to JRuby_

* ext/coverage/coverage.c
  - [x] Coverage.peek_result: new method to allow coverage to be captured without
    stopping the coverage tool. #3481

**Comment by headius** [comment]
We have completed everything we're likely to finish from this list for 9.1. I've filed #3816 for remaining and late-breaking items from MRI's final 2.3.0 NEWS file.
