### ISSUE TITLE
Ruby 2.4 support

### ISSUE THREAD

**Issue by headius** [jruby/jruby#4293]
This bug will track all NEWS items new in Ruby 2.4. This list is based off https://github.com/ruby/ruby/blob/trunk/NEWS.

Only changes relevant to JRuby are listed here. MRI-specific internal changes and features are not included.

NOTE: Pull requests should be done against the `ruby-2.4` branch.

### Language changes

* [x] Multiple assignment in conditional expression is now allowed. [Feature #10617](https://bugs.ruby-lang.org/issues/10617)

* [ ] Refinements is enabled at method by Symbol#to_proc.  [Feature #9451](https://bugs.ruby-lang.org/issues/9451)

* [ ] Refinements is enabled with Kernel#send and BasicObject#\_\_send\_\_. [Feature #11476](https://bugs.ruby-lang.org/issues/11476)

* [x] Rescue modifier now applicable to method arguments. [Feature #12686](https://bugs.ruby-lang.org/issues/12686)

* [ ] Toplevel return is now allowed. [Feature #4840](https://bugs.ruby-lang.org/issues/4840)

### Core classes updates (outstanding ones only)

* Array

  * [x] Array#max and Array#min.  [Feature #12172](https://bugs.ruby-lang.org/issues/12172)

  * [x] Array#sum  [Feature #12217](https://bugs.ruby-lang.org/issues/12217)

  * [x] Array#concat [Feature #12333](https://bugs.ruby-lang.org/issues/12333)

  * [x] Array#pack now takes optional argument `buffer:` to reuse an already-allocated buffer. [Feature #12217](https://bugs.ruby-lang.org/issues/12217)

* Comparable

  * [x] Comparable#clamp.  [Feature #10594](https://bugs.ruby-lang.org/issues/10594)

* Dir

  * [x] Dir.empty?.  [Feature #10121](https://bugs.ruby-lang.org/issues/10121)

* Enumerable

  * [x] Enumerable#sum  [Feature #12217](https://bugs.ruby-lang.org/issues/12217)
  * [x] Enumerable#uniq  [Feature #11090](https://bugs.ruby-lang.org/issues/11090)
  * [x] Enumerable#chunk called without a block now return an Enumerator. [Feature #2172](https://bugs.ruby-lang.org/issues/2172)

* Enumerator::Lazy

  * [x] Enumerator::Lazy#chunk_while  [GH-1186](https://github.com/ruby/ruby/pull/1186)
  * [x] Enumerator::Lazy#uniq  [Feature #11090](https://bugs.ruby-lang.org/issues/11090)

* File

  * [x] File.empty?.  [Feature #9969](https://bugs.ruby-lang.org/issues/9969)

* Float

  * [x] Float#ceil, Float#floor, and Float#truncate now take an optional digits, as well as Float#round.  [Feature #12245](https://bugs.ruby-lang.org/issues/12245)

  * [x] Float#round now takes an optional keyword argument, half option, and
    the default behavior is round-up.  [Bug #12548](https://bugs.ruby-lang.org/issues/12548) [Bug #12958](https://bugs.ruby-lang.org/issues/12958)
    half option can be one of :even, :up, and :down.  [Feature #12953](https://bugs.ruby-lang.org/issues/12953)

* Hash

  * [x] Hash#transform_values and Hash#transform_values!  [Feature #12512](https://bugs.ruby-lang.org/issues/12512)
  * [x] Hash#compact and Hash#compact!  [Feature #11818](https://bugs.ruby-lang.org/issues/11818)

* Integer

  * [x] Integer#ceil, Integer#floor, and Integer#truncate now take an optional digits, as well as Integer#round.  [Feature #12245](https://bugs.ruby-lang.org/issues/12245)

  * [x] Fixnum and Bignum are unified into Integer  [Feature #12005](https://bugs.ruby-lang.org/issues/12005)

  * [x] Integer#digits for extracting columns of place-value notation [Feature #12447](https://bugs.ruby-lang.org/issues/12447)

  * [x] Integer#round now takes an optional keyword argument, half option, and
    the default behavior is round-up.  [Bug #12548](https://bugs.ruby-lang.org/issues/12548) [Bug #12958](https://bugs.ruby-lang.org/issues/12958)
    half option can be one of :even, :up, and :down.  [Feature #12953](https://bugs.ruby-lang.org/issues/12953)

* IO

  * [x] IO#gets, IO#readline, IO#each_line, IO#readlines, IO.foreach now takes an optional keyword argument, chomp flag.  [Feature #12553](https://bugs.ruby-lang.org/issues/12553)

* Kernel

  * [x] Kernel#clone now takes an optional keyword argument, freeze flag. [Feature #12300](https://bugs.ruby-lang.org/issues/12300)

* MatchData

  * [x] MatchData#named_captures [Feature #11999](https://bugs.ruby-lang.org/issues/11999)
  * [x] MatchData#values_at supports named captures [Feature #9179](https://bugs.ruby-lang.org/issues/9179)

* Module

  * [ ] Module.used_modules [Feature #7418](https://bugs.ruby-lang.org/issues/7418)
  * [ ] Module#refine accepts a module as the argument now. [Feature #12534](https://bugs.ruby-lang.org/issues/12534)

* Numeric

  * [x] Numeric#finite?, Numeric#infinite? [Feature #12039](https://bugs.ruby-lang.org/issues/12039)

* Process

  * [ ] Support CLOCK_MONOTONIC_RAW_APPROX, CLOCK_UPTIME_RAW, and CLOCK_UPTIME_RAW_APPROX which are introduced by macOS 10.12.

* Rational

  * [x] Rational#round now takes an optional keyword argument, half option, and
    the default behavior is round-up.  [Bug #12548](https://bugs.ruby-lang.org/issues/12548) [Bug #12958](https://bugs.ruby-lang.org/issues/12958)
    half option can be one of :even, :up, and :down.  [Feature #12953](https://bugs.ruby-lang.org/issues/12953)

* Regexp

  * [x] Regexp#match? [Feature #8110](https://bugs.ruby-lang.org/issues/8110)
  * [ ] meta character \\X matches Unicode 9.0 characters with some workarounds for UTR #51 Unicode Emoki, Version 4.0 emoji zwj sequences
  * [ ] Update Onigmo 6.0.0 (we have never incorporated all of Onigmo's additions into Joni)

* [ ] Regexp/String: Updated Unicode version from 8.0.0 to 9.0.0 [Feature #12513](https://bugs.ruby-lang.org/issues/12513)

* String

  * [ ] String#upcase, String#downcase, String#capitalize, String#swapcase and their bang variants work for all of Unicode, and are no longer limited to ASCII. Supported encodings are UTF-8, UTF-16BE/LE, UTF-32BE/LE, and ISO-8859-1~16. Variations are available with options. See the documentation of String#downcase for details. [Feature #10085](https://bugs.ruby-lang.org/issues/10085)

  * [x] String.new(capacity: size) [Feature #12024](https://bugs.ruby-lang.org/issues/12024)

  * [x] String#concat, String#prepend [Feature #12333](https://bugs.ruby-lang.org/issues/12333) Now takes multiple arguments.

  * [x] String#unpack1 [Feature #12752](https://bugs.ruby-lang.org/issues/12752)

  * [x] String#match? [Feature #12898](https://bugs.ruby-lang.org/issues/12989)

  * [x] String#each_line, String#lines now takes an optional keyword argument, chomp flag. [Feature #12553](https://bugs.ruby-lang.org/issues/12553)

  * [x] String#concat, String#prepend now take multiple arguments [Feature #12333](https://bugs.ruby-lang.org/issues/12333)

  * [x] String#casecmp? [Feature #12786](https://bugs.ruby-lang.org/issues/12786)

* StringIO

  * [x] StringIO#gets, StringIO#readline, StringIO#each_line, StringIO#readlines now take optional keyword argument, chomp flag. [Feature #12553](https://bugs.ruby-lang.org/issues/12553)

* Symbol

  * [x] Symbol#match now returns MatchData.  [Bug #11991](https://bugs.ruby-lang.org/issues/11991)

  * [ ] Symbol#upcase, Symbol#downcase, Symbol#capitalize, and Symbol#swapcase now work for all of Unicode. See the documentation of String#downcase for details. [Feature #10085](https://bugs.ruby-lang.org/issues/10085)

  * [x] Symbol#match? [Feature #12898](https://bugs.ruby-lang.org/issues/12898)

  * [x] Symbol#casecmp? [Feature #12786](https://bugs.ruby-lang.org/issues/12786)

* Thread

  * [x] Thread#report_on_exception and Thread.report_on_exception [Feature #6647](https://bugs.ruby-lang.org/issues/6647)

* TracePoint

  * [ ] TracePoint#callee_id [Feature #12747](https://bugs.ruby-lang.org/issues/12747)

* Warning

  * [x] New module named Warning is introduced.  By default it has only one singleton method, named warn.  This makes it possible for 3rd-party libraries to control the way warnings are handled. [Feature #12299](https://bugs.ruby-lang.org/issues/12299)

### Stdlib updates (only items that need specific attention in JRuby)

* pathname

  * [x] New method: Pathname#empty? [Feature #12596](https://bugs.ruby-lang.org/issues/12596)

* Readline

  * [ ] Readline.quoting_detection_proc and Readline.quoting_detection_proc= [Feature #12659](https://bugs.ruby-lang.org/issues/12659)

### Compatibility issues (excluding feature bug fixes)

* [x] Array#sum and Enumerable#sum are implemented.  [Feature #12217](https://bugs.ruby-lang.org/issues/12217)

* [x] Fixnum and Bignum are unified into Integer  [Feature #12005](https://bugs.ruby-lang.org/issues/12005)

* [ ] String/Symbol#upcase/downcase/swapcase/capitalize(!) now work for all of Unicode, not only for ASCII. [Feature #10085](https://bugs.ruby-lang.org/issues/)

* [x] TRUE / FALSE / NIL These constants are now obsoleted. [Feature #12574](https://bugs.ruby-lang.org/issues/12574)

### Stdlib compatibility issues (excluding feature bug fixes)

* DateTime

  * [x] DateTime#to_time now preserves timezone.  [Bug #12189](https://bugs.ruby-lang.org/issues/12189)

* Psych
  * [x] Update Psych 2.2.2

* RDoc

  * [x] Update RDoc 5.0.0

* RubyGems

  * [x] Update RubyGems 2.6.8

* Time

  * [x] Time#to_time now preserves timezone.  [Bug #12271](https://bugs.ruby-lang.org/issues/12271)

* thread

  * [x] the extension library is removed.  Till 2.0 it was a pure ruby script "thread.rb", which has precedence over "thread.so", and has been provided in $LOADED_FEATURES since 2.1.

* Zlib
  * [x] Zlib.gzip and Zlib.gunzip [Feature #13020](https://bugs.ruby-lang.org/issues/13020)

### Implementation improvements

* [ ] In some condition, `[x, y].max` and `[x, y].min` are optimized so that a temporal array is not created.  The concrete condition is an implementation detail: currently, the array literal must have no splat, must have at least one expression but literal, the length must be <= 0x100, and Array#max and min must not be redefined.  It will work in most casual and real-life use case where it is written with intent to `Math.max(x, y)`.

* [ ] Thread deadlock detection now shows their backtrace and dependency. [Feature #8214](https://bugs.ruby-lang.org/issues/8214)

* [ ] st_table (st.c) internal data structure is improved. [Feature #12142](https://bugs.ruby-lang.org/issues/12142)

* [ ] Rational is extensively optimized. [Feature #12484](https://bugs.ruby-lang.org/issues/12484)

**Comment by ianks** [comment]
Which of these should be implemented in ruby?

**Comment by headius** [comment]
@ianks Any that make sense! Obviously some things, like potential Hash optimizations, would have to be in Java, but many of these features would be just fine in Ruby. See https://github.com/jruby/jruby/tree/master/core/src/main/ruby/jruby/kernel.

**Comment by headius** [comment]
Note that for `[x, y].max`, JRuby 9.1.5.0+ already allocates a smaller object to hold `x, y`. Remaining work would be enhancements to the IR builder to optimize this structure to just do the comparison.

**Comment by abotalov** [comment]
By the way, https://github.com/ruby/ruby/blob/trunk/doc/NEWS-2.4.0 lists a few more updates now.

**Comment by headius** [comment]
@abotalov Thanks! Now that it's final I'll do one more update of this list.

**Comment by headius** [comment]
Unless there are late-breaking additions, I think this is what we're settling on for 2.4 support in the initial JRuby 9.2 release. We'll continue to track missing 2.4 features at https://github.com/jruby/jruby/issues/4687 and related issues.
