### ISSUE TITLE
Unimplemented Ruby 2.5 Features

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5118]
This bug tracks the remaining items from CRuby 2.5's NEWS file that we have not yet implemented in JRuby.

This issue will track Ruby 2.5 support for JRuby. This will be released in JRuby 9.3.0.0 or JRuby 10.

As with previous releases, we will base our checklist on MRI's NEWS file: https://github.com/ruby/ruby/blob/trunk/NEWS
This bug will track all NEWS items new in Ruby 2.5. This list is based off https://github.com/ruby/ruby/blob/trunk/NEWS.

Only changes relevant to JRuby are listed here. MRI-specific internal changes and features are not included.

### Language changes

- [x] refinements take place in string interpolations.  [Feature #13812](https://bugs.ruby-lang.org/issues/13812)

#### File

- [ ]  :newline option to `File.open` implies text mode now.  [Bug #13350](https://bugs.ruby-lang.org/issues/13350)

#### IO

- [ ] `IO#pread`  [Feature #4532](https://bugs.ruby-lang.org/issues/4532)
- [ ] `IO#pwrite`  [Feature #4532](https://bugs.ruby-lang.org/issues/4532)
- [ ] `IO#copy_stream` tries copy offload with `copy_file_range(2)` [Feature #13867](https://bugs.ruby-lang.org/issues/13867)

#### Process

- [ ] Precision of `Process.times` is improved if `getrusage(2)` exists. [Feature #11952](https://bugs.ruby-lang.org/issues/11952)

#### Range

- [x] `Range#initialize` no longer rescue exceptions when comparing begin and
    end with `#<=>` and raise a "bad value for range" ArgumentError
    but instead let the exception from the `#<=>` call go through.
    [Feature #7688](https://bugs.ruby-lang.org/issues/7688)

#### Regexp

- [ ] Update to Onigmo 6.1.1.
- [x] Support absent operator https://github.com/k-takata/Onigmo/issues/82

#### BasicSocket

- [ ] `BasicSocket#read_nonblock` and `BasicSocket#write_nonblock` no longer sets the O_NONBLOCK file description flag as side effect (on Linux only) [Feature #13362](https://bugs.ruby-lang.org/issues/13362)
### Implementation improvements

(Probably not JRuby-relevant.)

* This might not be a "user visible feature change" but) Hash class's
  hash function is now SipHash13. [Feature #13017](https://bugs.ruby-lang.org/issues/13017)
* SecureRandom now prefers OS-provided sources than OpenSSL. [Bug #9569](https://bugs.ruby-lang.org/issues/9569)
* Mutex rewritten to be smaller and faster [Feature #13517](https://bugs.ruby-lang.org/issues/13517)
* Performance of block passing using block parameters is improved by lazy Proc allocation [Feature #14045](https://bugs.ruby-lang.org/issues/14045)
* Dynamic instrumentation for TracePoint hooks instead of using "trace" instruction to avoid overhead [Feature #14104](https://bugs.ruby-lang.org/issues/14104)

### Miscellaneous changes

- [ ] Print backtrace and error message in reverse order if STDERR is unchanged and a tty. [Feature #8661](https://bugs.ruby-lang.org/issues/8661) [experimental] (Started in #5094)
- [ ] Print error message in bold/underlined text if STDERR is unchanged and a tty. [Feature #14140](https://bugs.ruby-lang.org/issues/14140) [experimental] (Started in #5094)

**Comment by headius** [comment]
Marking for 9.2 optimistically, but some parts of this will obviously slip.

**Comment by headius** [comment]
Link #4876, #4875

**Comment by headius** [comment]
Most of these were done, and others are not relevant or very low priority.

#5510 covers backward traces. Additional formatting will come along with that.

#5816 covers the missing pread and pwrite.

#5817 covers the missing :newline keyword for File.open.

The nonblock changes are not relevant to JRuby on JDK since we can't specify MSG_DONTWAIT.

Process.times resolution is limited to what the JDK provides us; calling down to native would moot the purpose of calling a more accurate API.
