### ISSUE TITLE
JRuby 9.2 Projects

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5119]
We have many side projects in flight and no place to track them. I'm creating this list so we remember all the things we hope to ship in 9.2.

- [x] Ruby 2.5 support: largely complete, see #5118 and #4875.
- [x] New block dispatch, optimization: https://github.com/jruby/jruby/tree/block_dispatch
- [x] Encoding work for identifiers, symbols: (see #4965)
- [ ] Finish native process, IO logic for Windows: #4964, #5100, #1187, #3705, #4076, #3116 and others
- [x] Proper AOT support: currently AOT just compiles to IR and serializes it into a .class. We can produce actually-compiled .class that jlink, jaotc, appcds can do a lot with.
- [ ] Profiling and inlining of IR: https://github.com/jruby/jruby/tree/profiler
- [x] Full refinements support: partial and spotty right now
- [ ] CRuby look-alike API: see [org.jruby.api.API](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/api/API.java). Most of what would live here already exists, and just needs a stub.
- [x] Pure-Ruby Enumerable: #4108, #5044
- [x] Reimplement Enumerator#next with Fiber: #4212, #2577

- [x] Reimplement Set/SortedSet (set.rb) in native with JI support: #4690
- [x] Reimplement Date/DateTime (date.rb library) in native: #5076
- [x] support Java 8 date-time APIs (`to_java`) with Ruby types - Time/Date/DateTime

From https://github.com/jruby/jruby/issues/4293:

* String
  * [x] String#upcase, String#downcase, String#capitalize, String#swapcase and their bang variants work for all of Unicode, and are no longer limited to ASCII. Supported encodings are UTF-8, UTF-16BE/LE, UTF-32BE/LE, and ISO-8859-1~16. Variations are available with options. See the documentation of String#downcase for details. [Feature #10085](https://bugs.ruby-lang.org/issues/10085)

* Symbol
  * [x] Symbol#upcase, Symbol#downcase, Symbol#capitalize, and Symbol#swapcase now work for all of Unicode. See the documentation of String#downcase for details. [Feature #10085](https://bugs.ruby-lang.org/issues/10085)

**Comment by headius** [comment]
Enumerator-on-Fiber is already in for 9.2.8.0. I updated the checklist.

**Comment by headius** [comment]
Mostly-full refinements support went into 9.2.7.0 and closed all known user issues. There are a few failing tests but mostly along weird edges like using "undef_method" against refined methods.

Ruby 2.5 support shipped in 9.2 and the remaining gaps have largely been closed in releases since then.

**Comment by headius** [comment]
Block dispatch and AOT support are improved in 9.2.10 and 9.3 respectively. The other items have their own issues elsewhere, so I'll kill this one.
