### ISSUE TITLE
Ruby 2.6 Support

### ISSUE THREAD

**Issue by anubhav8421** [jruby/jruby#5576]
This issue will track Ruby 2.6 support for JRuby. This will be released in JRuby 9.3.0.0

As with previous releases, we will base our checklist on MRI's NEWS file: https://github.com/ruby/ruby/blob/ruby_2_6/NEWS
This bug will track all NEWS items new in Ruby 2.6. This list is based off https://github.com/ruby/ruby/blob/ruby_2_6/NEWS.

Only changes relevant to JRuby are listed here. MRI-specific internal changes and features are not included.

NOTE: Pull requests should be done against the ```ruby-2.6``` branch. That branch will be merged via #6037.

## Language changes

- [ ] Refinements take place at block passing [Feature #14223](https://bugs.ruby-lang.org/issues/14223)
- [ ] Refinements take place at Kernel#public_send [Feature #15326](https://bugs.ruby-lang.org/issues/15326)
- [ ] Refinements take place at Kernel#respond_to? [Feature #15327](https://bugs.ruby-lang.org/issues/15327)
- [x] ```else``` without ```rescue``` causes a syntax error [Experimental] [Feature #14606](https://bugs.ruby-lang.org/issues/14606)
- [x] Constant names may start with a non-ASCII capital letter [Feature #13770](https://bugs.ruby-lang.org/issues/13770)
- [x] Endless ranges are introduced. Range that has no end, like ```(0..)``` or ```(0...)``` [Feature #12912](https://bugs.ruby-lang.org/issues/12912)
- [ ] Non-Symbol keys in a keyword arguments hash cause an exception.
- [x] The “shadowing outer local variable” warning is removed.  [Feature #12490](https://bugs.ruby-lang.org/issues/12490)
- [ ] Print ```cause``` of the exception if the exception is not caught and printed its backtraces and error message. [Feature #8257](https://bugs.ruby-lang.org/issues/8257)
- [x] The flip-flop syntax is deprecated. [Feature #5400](https://bugs.ruby-lang.org/issues/5400)

### Array

- [x] Add Array#union and Array#difference instance methods. [Feature #14097](https://bugs.ruby-lang.org/issues/14097)
- [x] Array#to_h now accepts a block that maps elements to new key/value pairs. [Feature #15143](https://bugs.ruby-lang.org/issues/15143)
- [x] Array#filter is a new alias for Array#select. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)
- [x] Array#filter! is a new alias for Array#select!. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

### Binding

- [x] Added Binding#source_location. [Feature #14230](https://bugs.ruby-lang.org/issues/14230)

### Dir

- [x] Added Dir#each_child and Dir#children instance methods. [Feature #13969](https://bugs.ruby-lang.org/issues/13969)

### Enumerable

- [x] Enumerable#chain returns an enumerator object that iterates over the elements of the receiver and then those of each argument in sequence. [Feature #15144](https://bugs.ruby-lang.org/issues/15144)
- [x] Enumerable#to_h now accepts a block that maps elements to new key/value pairs. [Feature #15143](https://bugs.ruby-lang.org/issues/15143)
- [x] Enumerable#filter is a new alias for Enumerable#select. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

### Enumerator::ArithmeticSequence

- [x] This is a new class to represent a generator of an arithmetic sequence, that is a number sequence defined by a common difference. It can be used for representing what is similar to Python's slice. You can get an instance of this class from Numeric#step and Range#step.

### Enumerator::Chain

- [x] This is a new class to represent a chain of enumerables that works as a single enumerator, generated by such methods as Enumerable#chain and Enumerator#+.

### Enumerator::Lazy

- [x] Enumerator::Lazy#filter is a new alias for Enumerator::Lazy#select. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

### Enumerator

- [x] Enumerator#+ returns an enumerator object that iterates over the elements of the receiver and then those of the other operand. [Feature #15144](https://bugs.ruby-lang.org/issues/15144)

### ENV

- [x] ENV.to_h now accepts a block that maps names and values to new keys and values. [Feature #15143](https://bugs.ruby-lang.org/issues/15143)

### Exception

- [ ] Exception#full_message takes ```:highlight``` and ```:order options```. [Bug #14324](https://bugs.ruby-lang.org/issues/14324)

### Hash

- [x] Hash#merge, Hash#merge!, and Hash#update now accept multiple arguments. [Feature #15111](https://bugs.ruby-lang.org/issues/15111)
- [x] Hash#to_h now accepts a block that maps keys and values to new keys and values. [Feature #15143](https://bugs.ruby-lang.org/issues/15143)
- [x] Hash#filter is a new alias for Hash#select. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)
- [x] Hash#filter! is a new alias for Hash#select!. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

### IO

- [x] Added new mode character ```'x'``` to open files for exclusive access. [Feature #11258](https://bugs.ruby-lang.org/issues/11258)

### Kernel

- [x] Kernel#then is a new alias for Kernel#yield_self. [Feature #14594](https://bugs.ruby-lang.org/issues/14594)
- [x] Kernel#Complex, Kernel#Float, Kernel#Integer, and Kernel#Rational take an ```:exception``` option to specify the way of error handling. [Feature #12732](https://bugs.ruby-lang.org/issues/12732)
- [x] Kernel#system takes an ```:exception``` option to raise an exception on failure. [Feature #14386](https://bugs.ruby-lang.org/issues/14386)
- [x] Kernel#system and Kernel#exec do not close non-standard file descriptors (the default of the ```:close_others``` option is changed to ```false```, but we still set the ```FD_CLOEXEC``` flag on descriptors we create). [Misc #14907](https://bugs.ruby-lang.org/issues/14907)

### KeyError

- [x] KeyError.new accepts ```:receiver``` and ```:key``` options to set receiver and key in Ruby code. [Feature #14313](https://bugs.ruby-lang.org/issues/14313)

### Method

- [x] Added Method#<< and Method#>> for Proc composition. [Feature #6284](https://bugs.ruby-lang.org/issues/6284)

### Module

- [x] Module#method_defined?, Module#private_method_defined?, and Module#protected_method_defined? now accept the second parameter as optional. [Feature #14944](https://bugs.ruby-lang.org/issues/14944)

### NameError

- [ ] NameError.new accepts a ```:receiver``` option to set receiver in Ruby code. [Feature #14313](https://bugs.ruby-lang.org/issues/14313)

### NilClass

- [x] NilClass#=~ is added for compatibility. [Feature #15231](https://bugs.ruby-lang.org/issues/15231)

### NoMethodError

- [ ] NoMethodError.new accepts a ```:receiver``` option to set receiver in Ruby code. [Feature #14313](https://bugs.ruby-lang.org/issues/14313)

### Numeric

- [x] Numeric#step now returns an instance of the Enumerator::ArithmeticSequence class rather than one of the Enumerator class.

### OpenStruct

- [x] OpenStruct#to_h now accepts a block that maps keys and values to new keys and values. [Feature #15143](https://bugs.ruby-lang.org/issues/15143)

### Proc

- [x] Added Proc#<< and Proc#>> for Proc composition. [Feature #6284](https://bugs.ruby-lang.org/issues/6284)
- [x] Proc#call doesn't change ```$SAFE``` any more. [Feature #14250](https://bugs.ruby-lang.org/issues/14250)

### Random

- [x] Added Random.bytes. [Feature #4938](https://bugs.ruby-lang.org/issues/4938)

### Range

- [x] Added Range#% instance method. [Feature #14697](https://bugs.ruby-lang.org/issues/14697)
- [x] Range#=== now uses the ```#cover?``` instead of the ```#include?``` method. [Feature #14575](https://bugs.ruby-lang.org/issues/14575)
- [x] Range#cover? now accepts a Range object. [Feature #14473](https://bugs.ruby-lang.org/issues/14473)
- [x] Range#step now returns an instance of the Enumerator::ArithmeticSequence class rather than one of the Enumerator class.

### Regexp/String

- [x] Update Unicode version from 10.0.0 to 11.0.0. [Feature #14802](https://bugs.ruby-lang.org/issues/14802)
- Updated to 12.0.0 as of https://github.com/ruby/ruby/commit/cff7eefa07f8e7bccb5c0b8c856e5657d6d45ffa
- [x] Update Emoji version from 5.0 to 11.0.0 [Feature #14802](https://bugs.ruby-lang.org/issues/14802)

### String

- [x] String#crypt is now deprecated. [Feature #14915](https://bugs.ruby-lang.org/issues/14915)
- [x] String#split yields each substring to the block if given. [Feature #4780](https://bugs.ruby-lang.org/issues/4780)

### Struct

- [x] Struct#to_h now accepts a block that maps keys and values to new keys and values. [Feature #15143](https://bugs.ruby-lang.org/issues/15143)
- [x] Struct#filter is a new alias for Struct#select. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

### Time

- [x] Time.new and Time#getlocal accept a timezone object as well as a UTC offset string. Time#+, Time#-, and Time#succ also preserve the timezone. [Feature #14850](https://bugs.ruby-lang.org/issues/14850)

### TracePoint

- [ ] “script_compiled” event is supported. [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [ ] TracePoint#parameters [Feature #14694](https://bugs.ruby-lang.org/issues/14694)
- [ ] TracePoint#instruction_sequence [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [ ] TracePoint#eval_script [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [ ] TracePoint#enable accepts new keywords “target:” and “target_line:”.[Feature #15289](https://bugs.ruby-lang.org/issues/15289)

### BigDecimal

- [ ] BigDecimal() accepts the new keyword “exception:” similar to Float().

##### The differences among recent versions of bigdecimal. Please select the suitable version of bigdecimal according to the following information.

- 1.3.5 has BigDecimal.new without “exception:” keyword. You can see the deprecation warning of BigDecimal.new when you specify “-w” option. BigDecimal(), BigDecimal.new, and Object#to_d methods are the same.
- 1.4.0 has BigDecimal.new with “exception:” keyword. You always see the deprecation warning of BigDecimal.new. Object#to_d method is different from BigDecimal() and BigDecimal.new.
- 2.0.0 will be released soon after releasing Ruby 2.6.0. This version will not have the BigDecimal.new method.

### Bundler

- [x] Add Bundler to Standard Library. [Feature #12733](https://bugs.ruby-lang.org/issues/12733)
- [x] Use 1.17.2, the latest stable version.

### Coverage

- [ ] A oneshot_lines mode is added. [Feature #15022](https://bugs.ruby-lang.org/issues/15022)
- [ ] Add ```:oneshot_lines``` keyword argument to Coverage.start.
- [ ] Add ```:stop``` and ```:clear``` keyword arguments to Coverage.result. If ```clear``` is true, it clears the counters to zero. If ```stop``` is true, it disables coverage measurement.
- [ ] Coverage.line_stub, which is a simple helper function that creates the “stub” of line coverage from a given source code.

### CSV
- [x] Upgrade to 3.0.2. This includes performance improvements especially for writing. Writing is about 2 times faster. See github.com/ruby/csv/blob/master/NEWS.md.

### ERB

- [x] Add ```:trim_mode``` and ```:eoutvar``` keyword arguments to ERB.new. Now non-keyword arguments other than the first one are softly deprecated and will be removed when Ruby 2.5 becomes EOL. [Feature #14256](https://bugs.ruby-lang.org/issues/14256)
- [x] erb command's ```-S``` option is deprecated, and will be removed in the next version.

### FileUtils

- [x] FileUtils#cp_lr. [Feature #4189](https://bugs.ruby-lang.org/issues/4189)

### Matrix

- [x] Matrix#antisymmetric?, Matrix#skew_symmetric?
- [x] Matrix#map!, Matrix#collect! [Feature #14151](https://bugs.ruby-lang.org/issues/14151)
- [x] Matrix#[]=
- [x] Vector#map!, Vector#collect!
- [x] Vector#[]=

### Net

- [x] Add ```:write_timeout``` keyword argument to Net::HTTP.new. [Feature #13396](https://bugs.ruby-lang.org/issues/13396)
- [x] Add Net::HTTP#write_timeout and Net::HTTP#write_timeout=. [Feature #13396](https://bugs.ruby-lang.org/issues/13396)
- [x] Add Net::HTTPClientException to deprecate Net::HTTPServerException, whose name is misleading. [Bug #14688](https://bugs.ruby-lang.org/issues/14688)

### NKF

- [ ] Upgrade to nkf v2.1.5

### Psych

- [x] Upgrade to Psych 3.1.0

### RDoc

- [x] Become about 2 times faster.
- [x] Use SOURCE_DATE_EPOCH to generate files.
- [x] Fix method line number that slipped off.
- [x] Enable ```--width```, ```--exclude```, and ```--line-numbers``` that were ignored.
- [x] Add support for blockquote by “>>>” in default markup notation.
- [x] Add support for “Raises” lines in TomDoc notation.
- [x] Fix syntax error output.
- [x] Fix many parsing bugs.

### REXML

- [x] Upgrade to REXML 3.1.9. See (github.com/ruby/rexml/blob/master/NEWS.md).
- [x] ```concat()``` function: Stringify all arguments before concatenating.
- [x] ```string()``` function: Support context node.
- [x] ```string()``` function: Support processing instruction node.
- [x] Support ```"*:#{ELEMENT_NAME}"``` syntax in XPath 2.0.
- [x] ```"//#{ELEMENT_NAME}[#{POSITION}]"``` case
- [x] ```string()``` function: Fix ```function(document)``` returns nodes that are out of root elements.
- [x] ```"/ #{ELEMENT_NAME} "``` case
- [x] ```"/ #{ELEMENT_NAME} [ #{PREDICATE} ]"``` case
- [x] ```"/ #{AXIS}::#{ELEMENT_NAME}"``` case
- [x] ```"#{N}-#{M}"``` case: One or more white spaces were required before ```"-"```
- [x] ```"/child::node()"``` case
- [x] ```"#{FUNCTION}()/#{PATH}"``` case
- [x] ```"@#{ATTRIBUTE}/parent::"``` case
- [x] ```"name(#{NODE_SET})"``` case

### CSV

- [x] Upgrade to 3.0.4. See (github.com/ruby/csv/blob/master/NEWS.md).

### RSS

- [x] RSS::Parser.parse now accepts options as Hash. ```:validate``` , ```:ignore_unknown_element``` , ```:parser_class``` options are available.

### RubyGems

- [x] Upgrade to RubyGems 3.0.1
- [x] (blog.rubygems.org/2018/12/19/3.0.0-released.html)
- [x] (blog.rubygems.org/2018/12/23/3.0.1-released.html)

### Set

- [x] Set#filter! is a new alias for Set#select!. [Feature #13784](https://bugs.ruby-lang.org/issues/13784)

### URI

- [x] Add URI::File to handle the file URI scheme. [Feature #14035](https://bugs.ruby-lang.org/issues/14035)

### Dir

- [ ] Dir.glob with ```'\0'```-separated pattern list will be deprecated, and is now warned. [Feature #14643](https://bugs.ruby-lang.org/issues/14643)

### File

- [ ] File.read, File.binread, File.write, File.binwrite, File.foreach, and File.readlines do not invoke external commands even if the path starts with the pipe character '|'. [Feature #14245](https://bugs.ruby-lang.org/issues/14245)

### Object

- [x] Object#=~ is deprecated. [Feature #15231](https://bugs.ruby-lang.org/issues/15231)

## Stdlib compatibility issues (excluding feature bug fixes)

These standard libraries have been promoted to default gems.

- [x] e2mmap
- [x] forwardable
- [x] irb
- [x] logger
- [ ] matrix
- [x] mutex_m
- [ ] ostruct
- [ ] prime
- [x] rexml
- [x] rss
- [x] shell
- [x] sync
- [x] thwait
- [ ] tracer

### BigDecimal

* The following methods are removed.
   - [x] BigDecimal.allocate
   - [x] BigDecimal.ver
- [x] Every BigDecimal object is frozen. [Feature #13984](https://bugs.ruby-lang.org/issues/13984)
- [x] BigDecimal() parses the given string similar to Float().
- [x] String#to_d parses the receiver string similar to String#to_f.
- [ ] BigDecimal.new will be removed in version 2.0.

### Pathname

- [ ] Pathname#read, Pathname#binread, Pathname#write, Pathname#binwrite, Pathname#each_line and Pathname#readlines do not invoke external commands even if the path starts with the pipe character ```'|'```. This follows [Feature #14245](https://bugs.ruby-lang.org/issues/14245)

**Comment by develop-build** [comment]
@enebo @nomadium I saw several PRs merged towards this direction. Request to update them.

**Comment by headius** [comment]
I feel like a bunch of these have been completed by other PRs. @develop-build Maybe you can review commits to this branch and check off any others that are complete (if you haven't already)>

**Comment by kares** [comment]
(we) did that (rebiew commits on ruby-2.6) after this issue was created ...as noted on irc/gitter at the tme.

**Comment by headius** [comment]
@kares @anubhav8421 Thanks!

**Comment by gsbhasin123** [comment]
Can't wait for this; 2.7 is coming up!

**Comment by k77ch7** [comment]
@anubhav8421  String#crypt still works without no warning on ruby 2.6.3 and 2.7.0-preview1.

**Comment by k77ch7** [comment]
Struct#filter works on ruby-2.6 branch(519dba1).

**Comment by headius** [comment]
@k77ch7 Thanks for looking into stuff!

The crypt deprecation should be easy; we just need to add a warning like CRuby.

I will mark Struct#filter and OpenStruct#to_h as complete.

**Comment by headius** [comment]
I have updated stdlib and tests from Ruby 2.6.5 on the ruby-2.6 branch. Proceeding to do a merge from master.

**Comment by headius** [comment]
I've merged master. There were a number of conflicts due to recent cleanup commits, so hopefully nothing got too borked.

**Comment by headius** [comment]
I have turned the branch into a PR here: #6037

**Comment by headius** [comment]
We are now moving forward with 9.3 development. I've done some work on updating the standard library in #6037 but it needs more work to be passing a high enough level to merge.

**Comment by headius** [comment]
The prime library has actually not been fully gemified yet because there's a squatter on the RubyGem name. I have unchecked that box and will re-commit the library from https://github.com/ruby/prime.

**Comment by headius** [comment]
Kernel#Complex and Kernel#Rational `:exception` kwarg support is partially landed.

**Comment by headius** [comment]
Like the `prime` library, `matrix` and `ostruct` had to be reverted to stdlib versions. All three can be switched back to gems once there's an updated gem released for each.

https://github.com/ruby/matrix/issues/12
https://github.com/ruby/ostruct/issues/11
https://github.com/ruby/prime/issues/11

**Comment by eregon** [comment]
@headius Why don't you import the sources of the default gems from the corresponding MRI version (like before they became default gems)?
There is always a chance the version in MRI is not exactly the same as a release.

**Comment by headius** [comment]
@eregon 

> Why don't you import the sources of the default gems

Isn't that what I said I did?

> There is always a chance the version in MRI is not exactly the same as a release.

That should definitely **NOT** be the case. If it's in an MRI release, and it's a default gem, there **MUST** be a gem release corresponding to that version of the library.

**Comment by eregon** [comment]
> Isn't that what I said I did?

Yes, but I meant just keep the in-repo version even after it becomes a default gem, just like MRI does.

**Comment by headius** [comment]
> I meant just keep the in-repo version even after it becomes a default gem

No, we should not be versioning files that are maintained elsewhere. We did so up to now solely because there are a few libraries with minor patches. The default gems will be exactly the same in JRuby, so they should be sourced from the released gems.

Except of course when they're not actually released, which is unfortunately the current situation.

We want to get away from having any of our own copies of Ruby stdlib in the repository, since they're not ours to maintain.

**Comment by headius** [comment]
The tracer library also needs a gem release. ruby/tracer#1

**Comment by headius** [comment]
I believe it's time to merge so I'm moving ongoing work to #6161 

A couple dozen of the remaining failures have been tagged off. Some will be completed before release.

Branch will be merged to master shortly.
