### ISSUE TITLE
Remaining Ruby 2.6 work

### ISSUE THREAD

**Issue by headius** [jruby/jruby#6161]
This issue is a catch-all for the unimplemented and tagged items during Ruby 2.6 compatibility work.

Original issue is #5576.

See also other incomplete issues #6149, #6157, #6158. #6159.

## Language changes

- [x] #8097
- [x] Refinements take place at Kernel#public_send [Feature #15326](https://bugs.ruby-lang.org/issues/15326)
- [x] Refinements take place at Kernel#respond_to? [Feature #15327](https://bugs.ruby-lang.org/issues/15327)
- [x] Non-Symbol keys in a keyword arguments hash cause an exception. (This was later reverted as it was problematic to make such a change in 2.6. The larger change to kwarg handling was deferred until Ruby 3.0, with some changes and warnings in 2.7. See #6878.)
- [x] The “shadowing outer local variable” warning is removed. [Feature #12490](https://bugs.ruby-lang.org/issues/12490)
- [x] Print ```cause``` of the exception if the exception is not caught and printed its backtraces and error message. [Feature #8257](https://bugs.ruby-lang.org/issues/8257) (https://github.com/jruby/jruby/pull/6889)

### Exception

- [x] Exception#full_message takes ```:highlight``` and ```:order options```. [Bug #14324](https://bugs.ruby-lang.org/issues/14324)

### NameError

- [x] NameError.new accepts a ```:receiver``` option to set receiver in Ruby code. [Feature #14313](https://bugs.ruby-lang.org/issues/14313)

### NoMethodError

- [x] NoMethodError.new accepts a ```:receiver``` option to set receiver in Ruby code. [Feature #14313](https://bugs.ruby-lang.org/issues/14313)

### TracePoint

These are not done but moved to https://github.com/jruby/jruby/issues/8098.

- [x] “script_compiled” event is supported. [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [x] TracePoint#parameters [Feature #14694](https://bugs.ruby-lang.org/issues/14694)
- [x] TracePoint#instruction_sequence [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [x] TracePoint#eval_script [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [x] TracePoint#enable accepts new keywords “target:” and “target_line:”.[Feature #15289](https://bugs.ruby-lang.org/issues/15289)

### Coverage

- [x] A oneshot_lines mode is added. [Feature #15022](https://bugs.ruby-lang.org/issues/15022)
- [x] Add ```:oneshot_lines``` keyword argument to Coverage.start.
- [x] Add ```:stop``` and ```:clear``` keyword arguments to Coverage.result. If ```clear``` is true, it clears the counters to zero. If ```stop``` is true, it disables coverage measurement.
- [x] Coverage.line_stub, which is a simple helper function that creates the “stub” of line coverage from a given source code.

### NKF

- [x] Upgrade to nkf v2.1.5

### Dir

- [x] Dir.glob with ```'\0'```-separated pattern list will be deprecated, and is now warned. [Feature #14643](https://bugs.ruby-lang.org/issues/14643) (JRuby never supported this behavior, so we consider it done)

### File

- [x] File.read, File.binread, File.write, File.binwrite, File.foreach, and File.readlines do not invoke external commands even if the path starts with the pipe character '|'. [Feature #14245](https://bugs.ruby-lang.org/issues/14245)

## Stdlib compatibility issues (excluding feature bug fixes)

These standard libraries have been promoted to default gems.

- [x] matrix
- [x] ostruct
- [x] prime
- [x] tracer

### BigDecimal

- [x] BigDecimal.new will be removed in version 2.0.
- [x] BigDecimal creation with `exception: false` never raises exception (still failing on master)

### Pathname

- [x] Pathname#read, Pathname#binread, Pathname#write, Pathname#binwrite, Pathname#each_line and Pathname#readlines do not invoke external commands even if the path starts with the pipe character ```'|'```. This follows [Feature #14245](https://bugs.ruby-lang.org/issues/14245)

**Comment by k77ch7** [comment]
@headius please review PR(https://github.com/jruby/jcodings/pull/31)
This PR fixes caseMap for Georgian.
I think you can remove the following exlclude tag.
```
 test/mri/excludes/TestCaseMappingPreliminary.rb 

 exclude :test_georgian_capitalize, "unfinished in initial 2.6 work, #6161"
```
Thank you.

**Comment by headius** [comment]
The `prime` and `tracer` gems have been released:

* https://rubygems.org/gems/prime
* https://rubygems.org/gems/tracer

**Comment by k77ch7** [comment]
@headius @lopex please review PR(jruby/jcodings#32)
This PR fixes treeStart for From_UTF8_MAC_Transcoder
I think you can remove the following exlclude tag.

```
TestTranscode.rb 
exclude :test_utf8_mac, "needs investigation"

&

TestCSVEncodings.rb 
exclude :test_reading_with_most_encodings, "needs investigation, #6157"
exclude :test_regular_expression_escaping, "needs investigation, #6157"
```

**Comment by headius** [comment]
@k77ch7 Good find! I was wondering why we failed those CSV tests.

jcodings has been released with your fix and I'll push an update to JRuby shortly.

**Comment by k77ch7** [comment]
@headius @lopex please review PR(jruby/jcodings#33)
This updates UTF32Encoding.
I think you can remove the following exlclude tag.
```
TestUTF32.rb
exclude :test_mbc_newline, "Java ArrayIndex error"
```

**Comment by headius** [comment]
Coverage's oneshot_lines mode was added in #6180. The missing `line_stub` method was added in #6185.

**Comment by headius** [comment]
@k77ch7 Updated jcodings and encoding excludes in 8a848bdb5d.

**Comment by k77ch7** [comment]
@headius Thank you.

**Comment by k77ch7** [comment]
I create 2 PR(jruby/jcodings#34 and jruby/jcodings#35) to reduce TestTranscode failures.

**Comment by headius** [comment]
@k77ch7 😍

**Comment by headius** [comment]
@k77ch7 It looks like the jcodings changes have been merged, so we could do another release. Do you have any other patches in the works that we should wait for?

**Comment by k77ch7** [comment]
@headius No, I don't have any patches now. But I'm investigating other encoding test cases.

**Comment by headius** [comment]
@k77ch7 @lopex jcodings has been released and updated on JRuby master.

**Comment by k77ch7** [comment]
@headius I create #6211 and jruby/jcodings#36 . 
I believe these will fix `test/mri/ruby/test_transcode.rb` failures.

**Comment by headius** [comment]
The matrix gem has a new release (ruby/matrix#12) so I've switched us back to using the gem.

* https://rubygems.org/gems/matrix

ostruct is the only remaining default gem for which we don't have a release.

@marcandre Thank you for getting an updated matrix release out! Only one to go!

**Comment by headius** [comment]
Bugger... apparently just  linking an issue to a PR willl close that issue. Bad design.

**Comment by k77ch7** [comment]
@headius I create jruby/jcodings#37 to reduce EncodingTest failures again.

**Comment by headius** [comment]
@k77ch7 I'll get it merged in, thanks!

**Comment by headius** [comment]
@k77ch7 Nice, those two tests have no excludes now!

**Comment by headius** [comment]
Detargeting; a few of these are not supportable, and some others have their own issues. We'll leave this in place as a record of the bits we have not finished.

**Comment by headius** [comment]
Actually most of the remaining items have been implemented or moved to their own issues.
