### ISSUE TITLE
Remaining fiber features for 3.0

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7438]
These features are unimplemented, but may be necessary for releasing 9.4.

* [x] Fiber.new(blocking: true/false) allows you to create non-blocking execution contexts. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]
* [x] Fiber#blocking? tells whether the fiber is non-blocking. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]
* [x] Fiber#backtrace and Fiber#backtrace_locations provide per-fiber backtrace. [[Feature #16815](https://bugs.ruby-lang.org/issues/16815)]
* [x] The limitation of Fiber#transfer is relaxed. [[Bug #17221](https://bugs.ruby-lang.org/issues/17221)]
* [ ] Introduce Fiber.set_scheduler for intercepting blocking operations and Fiber.scheduler for accessing the current scheduler. See rdoc-ref:fiber.md for more details about what operations are supported and how to implement the scheduler hooks. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]
* [x] Fiber.blocking? tells whether the current execution context is blocking. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]
* [ ] Thread#join invokes the scheduler hooks `block`/`unblock` in a non-blocking execution context. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]

**Comment by headius** [comment]
The remaining items are all related to the scheduler, which is a large known task we'll look at post-9.4.0.
