### ISSUE TITLE
Unfinished Ruby 3.0 features

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7459]
This is based on the list in #6878 and includes only the Ruby 3.0 features that were not implemented in time for the 9.4 release.

## Language changes

* [ ] #7457 Magic comment shareable_constant_value added to freeze constants.See {Magic Comments}[rdoc-ref:doc/syntax/comments.rdoc@Magic+Comments] for more details.
  [[Feature #17273](https://bugs.ruby-lang.org/issues/17273)] (Parses in JRuby but currently ignored due to not supporting Ractor)
* [ ] #7437 When a class variable is overtaken by the same definition in an ancestor class/module, a RuntimeError is now raised (previously, it only issued a warning in verbose mode). Additionally, accessing a class variable from the toplevel scope is now a RuntimeError.
  [[Bug #14541](https://bugs.ruby-lang.org/issues/14541)]

## Command line options
* [ ] `--help` option
   [[Feature #16754](https://bugs.ruby-lang.org/issues/16754)] (https://github.com/jruby/jruby/issues/7458)

## Core classes updates

ConditionVariable

* [ ]  ConditionVariable#wait may now invoke the `block`/`unblock` scheduler
  hooks in a non-blocking context. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]

ENV

* [ ]  Windows: Read ENV names and values as UTF-8 encoded Strings
  [[Feature #12650](https://bugs.ruby-lang.org/issues/12650)]

Encoding

* [ ]  Changed default for Encoding.default_external to UTF-8 on Windows
  [[Feature #16604](https://bugs.ruby-lang.org/issues/16604)]

IO

* [ ]  IO#nonblock? now defaults to `true`. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]
* [ ]  IO#wait_readable, IO#wait_writable, IO#read, IO#write and other
  related methods (e.g. IO#puts, IO#gets) may invoke the scheduler hook
  `#io_wait(io, events, timeout)` in a non-blocking execution context.
  [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]

Kernel

* [ ]  Kernel.sleep invokes the scheduler hook `#kernel_sleep(...)` in a
  non-blocking execution context. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]

Queue / SizedQueue

* [ ]  Queue#pop, SizedQueue#push and related methods may now invoke the
  `block`/`unblock` scheduler hooks in a non-blocking context.
  [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]

Ractor

* [ ]  New class added to enable parallel execution. See rdoc-ref:ractor.md for
  more details.

Fiber

* [ ]  Introduce Fiber.set_scheduler for intercepting blocking operations and
  Fiber.scheduler for accessing the current scheduler. See
  rdoc-ref:fiber.md for more details about what operations are supported and
  how to implement the scheduler hooks. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]
* [ ]  Thread#join invokes the scheduler hooks `block`/`unblock` in a
  non-blocking execution context. [[Feature #16786](https://bugs.ruby-lang.org/issues/16786)]

## Stdlib updates

Set

* [ ]  SortedSet has been removed for dependency and performance reasons. (Removed from `set` gem in https://github.com/ruby/set/pull/2, JRuby issue for `sorted_set` in https://github.com/knu/sorted_set/issues/7, PR to remove from JRuby in https://github.com/jruby/jruby/pull/6922)

Socket

* [ ]  Add :connect_timeout to TCPSocket.new [[Feature #17187](https://bugs.ruby-lang.org/issues/17187)]

## Compatibility issues
Excluding feature bug fixes.

* [ ]  When writing to STDOUT redirected to a closed pipe, no broken pipe
  error message will be shown now.  [[Feature #14413](https://bugs.ruby-lang.org/issues/14413)]

## Stdlib compatibility issues
* Default gems not yet supported on JRuby
    * [ ] debug
    * [ ] resolv
    * [ ] set
    * [ ] securerandom
    * [ ] tempfile
    * [ ] tmpdir
    * [ ] time
    * [ ] io-nonblock
    * [ ] nkf
    * [ ] pathname
    * [ ] syslog
    * [ ] win32ole

## Implementation improvements
* [ ]  New method cache mechanism for Ractor. [[Feature #16614](https://bugs.ruby-lang.org/issues/16614)]
  * Inline method caches pointed from ISeq can be accessed by multiple Ractors
    in parallel and synchronization is needed even for method caches. However,
    such synchronization can be overhead so introducing new inline method cache
    mechanisms, (1) Disposable inline method cache (2) per-Class method cache
    and (3) new invalidation mechanism. (1) can avoid per-method call
    synchronization because it only uses atomic operations.
    See the ticket for more details.
* [ ]  The number of hashes allocated when using a keyword splat in
  a method call has been reduced to a maximum of 1, and passing
  a keyword splat to a method that accepts specific keywords
  does not allocate a hash.
* [ ]  `super` is optimized when the same type of method is called in the previous call
  if it's not refinements or an attr reader or writer.

## Miscellaneous changes
* [ ]  When an exception is caught in the default handler, the error
  message and backtrace are printed in order from the innermost.
  [[Feature #8661](https://bugs.ruby-lang.org/issues/8661)]
