### ISSUE TITLE
Unfinished Ruby 3.1 features

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7460]
This is based on #7015 and includes only the items that we did not finish in time for 9.4.0.

## Language changes

* [ ] #7440 Multiple assignment evaluation order has been made consistent with single assignment evaluation order.  With single assignment, Ruby uses a left-to-right evaluation order.  With this code:

* [ ]   Non main-Ractors can get instance variables (ivars) of classes/modules
    if ivars refer to shareable objects.
    [[Feature #17592]]

## Core classes updates

* TracePoint

    * [ ]   TracePoint.allow_reentry is added to allow reenter while TracePoint
        callback.
        [[Feature #15912]]

* Fiber Scheduler

    * [ ]   Add support for `Addrinfo.getaddrinfo` using `address_resolve` hook.
        [[Feature #17370]]

    * [ ]   Introduce non-blocking `Timeout.timeout` using `timeout_after` hook.
        [[Feature #17470]]

    *  [ ]  Introduce new scheduler hooks `io_read` and `io_write` along with a
        low level `IO::Buffer` for zero-copy read/write. [[Feature #18020]]

    * [ ]   IO hooks `io_wait`, `io_read`, `io_write`, receive the original IO object
        where possible. [[Bug #18003]]

    * [ ]   Make `Monitor` fiber-safe. [[Bug #17827]]

    * [ ]   Replace copy coroutine with pthread implementation. [[Feature #18015]]

## Stdlib updates

* Default gems still not supported in JRuby
    * [ ] bigdecimal 3.1.1 (https://github.com/ruby/bigdecimal/issues/169)
    * [ ] date 3.2.2 (https://github.com/ruby/date/issues/48)
    * [ ] etc 1.3.0 (https://github.com/ruby/etc/issues/19)
    * [ ] fcntl 1.0.1 (https://github.com/ruby/fcntl/issues/9)
    * [ ] fiddle 1.1.0 (https://github.com/ruby/fiddle/issues/104)
    * [ ] nkf 0.1.1 (Partial implementation in JRuby, unsure whether this is important)
    * [ ] openssl 3.0.0 (https://github.com/ruby/openssl/issues/20#issuecomment-1022872855)
    * [ ] pathname 0.2.0 (https://github.com/ruby/pathname/issues/17)
    * [ ] readline 0.0.3 (https://github.com/ruby/readline/issues/5)
    * [ ] readline-ext 0.1.4 (will be solved along with readline)
    * [ ] resolv 0.2.1 (https://github.com/ruby/resolv/issues/19)
    * [ ] securerandom 0.1.1 (https://github.com/ruby/securerandom/issues/9)
    * [ ] set 1.0.2 (https://github.com/ruby/set/issues/21)
    * [ ] tempfile 0.1.2 (https://github.com/ruby/tempfile/issues/7)
    * [ ] time 0.2.0 (Depends on date)
    * [ ] tmpdir 0.1.2 (https://github.com/ruby/tmpdir/issues/13)
    * [ ] zlib 2.1.1 (https://github.com/ruby/zlib/issues/38)
*   The following bundled gems are updated.
    * [ ] rbs 2.0.0 (Depends on many internals of CRuby)
    * [ ] typeprof 0.21.1 (Depends on many internals of CRuby)
*   The following default gems are now bundled gems.
    * [ ] debug 1.4.0 (Depends on many internals of CRuby in newer versions)
* The following non-updated gems are not yet installable on JRuby.
    * [ ] gdbm 2.1.0
    * [ ] io-nonblock (https://github.com/ruby/io-nonblock/issues/4)
    * [ ] syslog 0.1.0 (https://github.com/ruby/syslog/issues/1)
    * [ ] win32ole 1.8.8 (https://github.com/ruby/win32ole/issues/12)

## Stdlib compatibility issues

* [ ] `lib/debug.rb` is replaced with `debug.gem`

## Implementation improvements

These do not apply directly to JRuby, but we should check if we have equivalent optimizations in place.

* Inline cache mechanism is introduced for reading class variables.
  [[Feature #17763]]

* `instance_eval` and `instance_exec` now only allocate a singleton class when
  required, avoiding extra objects and improving performance. [[GH-5146]]

* The performance of `Struct` accessors is improved. [[GH-5131]]

* `mandatory_only?` builtin special form to improve performance on
  builtin methods. [[GH-5112]]

* Experimental feature Variable Width Allocation in the garbage collector.
  This feature is turned off by default and can be enabled by compiling Ruby
  with flag `USE_RVARGC=1` set. [[Feature #18045]] [[Feature #18239]]

## Debugger

* [ ] A new debugger [debug.gem](https://github.com/ruby/debug) is bundled.
  debug.gem is a fast debugger implementation, and it provides many features
  like remote debugging, colorful REPL, IDE (VSCode) integration, and more.
  It replaces `lib/debug.rb` standard library.

* [ ] `rdbg` command is also installed into `bin/` directory to start and control
  debugging execution.

## Miscellaneous changes

* [ ] lib/objspace/trace.rb is added, which is a tool for tracing the object
  allocation. Just by requiring this file, tracing is started *immediately*.
  Just by `Kernel#p`, you can investigate where an object was created.
  Note that just requiring this file brings a large performance overhead.
  This is only for debugging purposes. Do not use this in production.
  [[Feature #17762]]

* [ ] Now exceptions raised in finalizers will be printed to `STDERR`, unless
  `$VERBOSE` is `nil`.  [[Feature #17798]]

* [ ] `ruby -run -e httpd` displays URLs to access.  [[Feature #17847]]

* [ ] Add `ruby -run -e colorize` to colorize Ruby code using
  `IRB::Color.colorize_code`.

[Bug #4443]:      https://bugs.ruby-lang.org/issues/4443
[Feature #6210]:  https://bugs.ruby-lang.org/issues/6210
[Feature #10917]: https://bugs.ruby-lang.org/issues/10917
[Feature #11256]: https://bugs.ruby-lang.org/issues/11256
[Feature #11689]: https://bugs.ruby-lang.org/issues/11689
[Feature #12194]: https://bugs.ruby-lang.org/issues/12194
[Feature #12495]: https://bugs.ruby-lang.org/issues/12495
[Feature #12913]: https://bugs.ruby-lang.org/issues/12913
[Feature #14256]: https://bugs.ruby-lang.org/issues/14256
[Feature #14579]: https://bugs.ruby-lang.org/issues/14579
[Feature #15198]: https://bugs.ruby-lang.org/issues/15198
[Feature #15211]: https://bugs.ruby-lang.org/issues/15211
[Feature #15912]: https://bugs.ruby-lang.org/issues/15912
[Feature #16043]: https://bugs.ruby-lang.org/issues/16043
[Feature #16182]: https://bugs.ruby-lang.org/issues/16182
[Feature #16806]: https://bugs.ruby-lang.org/issues/16806
[Feature #17312]: https://bugs.ruby-lang.org/issues/17312
[Feature #17327]: https://bugs.ruby-lang.org/issues/17327
[Feature #17370]: https://bugs.ruby-lang.org/issues/17370
[Feature #17398]: https://bugs.ruby-lang.org/issues/17398
[Feature #17411]: https://bugs.ruby-lang.org/issues/17411
[Bug #17423]:     https://bugs.ruby-lang.org/issues/17423
[Bug #17429]:     https://bugs.ruby-lang.org/issues/17429
[Feature #17470]: https://bugs.ruby-lang.org/issues/17470
[Feature #17479]: https://bugs.ruby-lang.org/issues/17479
[Feature #17485]: https://bugs.ruby-lang.org/issues/17485
[Feature #17544]: https://bugs.ruby-lang.org/issues/17544
[Feature #17592]: https://bugs.ruby-lang.org/issues/17592
[Feature #17684]: https://bugs.ruby-lang.org/issues/17684
[Feature #17724]: https://bugs.ruby-lang.org/issues/17724
[Feature #17744]: https://bugs.ruby-lang.org/issues/17744
[Feature #17750]: https://bugs.ruby-lang.org/issues/17750
[Feature #17762]: https://bugs.ruby-lang.org/issues/17762
[Feature #17763]: https://bugs.ruby-lang.org/issues/17763
[Feature #17795]: https://bugs.ruby-lang.org/issues/17795
[Feature #17798]: https://bugs.ruby-lang.org/issues/17798
[Bug #17827]:     https://bugs.ruby-lang.org/issues/17827
[Feature #17847]: https://bugs.ruby-lang.org/issues/17847
[Feature #17853]: https://bugs.ruby-lang.org/issues/17853
[Bug #17866]:     https://bugs.ruby-lang.org/issues/17866
[Bug #18003]:     https://bugs.ruby-lang.org/issues/18003
[Feature #18008]: https://bugs.ruby-lang.org/issues/18008
[Feature #18015]: https://bugs.ruby-lang.org/issues/18015
[Feature #18020]: https://bugs.ruby-lang.org/issues/18020
[Feature #18029]: https://bugs.ruby-lang.org/issues/18029
[Feature #18045]: https://bugs.ruby-lang.org/issues/18045
[Feature #18148]: https://bugs.ruby-lang.org/issues/18148
[Feature #18172]: https://bugs.ruby-lang.org/issues/18172
[Feature #18176]: https://bugs.ruby-lang.org/issues/18176
[Feature #18190]: https://bugs.ruby-lang.org/issues/18190
[Feature #18229]: https://bugs.ruby-lang.org/issues/18229
[Feature #18239]: https://bugs.ruby-lang.org/issues/18239
[Feature #18254]: https://bugs.ruby-lang.org/issues/18254
[Feature #18273]: https://bugs.ruby-lang.org/issues/18273
[Feature #18290]: https://bugs.ruby-lang.org/issues/18290

[GH-1509]: https://github.com/ruby/ruby/pull/1509
[GH-4815]: https://github.com/ruby/ruby/pull/4815
[GH-5112]: https://github.com/ruby/ruby/pull/5112
[GH-5131]: https://github.com/ruby/ruby/pull/5131
[GH-5146]: https://github.com/ruby/ruby/pull/5146
