### ISSUE TITLE
Ruby 3.2 support

### ISSUE THREAD

**Issue by headius** [jruby/jruby#7517]
# NEWS for Ruby 3.2.0

This document is a list of user-visible feature changes
since the **3.1.0** release, except for bug fixes.

Note that each entry is kept to a minimum, see links for details.

## Language changes

- [x] Anonymous rest and keyword rest arguments can now be passed as
  arguments, instead of just used in method parameters.
  [[Feature #18351]]

    ```ruby
    def foo(*)
      bar(*)
    end
    def baz(**)
      quux(**)
    end
    ```

- [x] A proc that accepts a single positional argument and keywords will
  no longer autosplat. [[Bug #18633]]

    ```ruby
    proc{|a, **k| a}.call([1, 2])
    # Ruby 3.1 and before
    # => 1
    # Ruby 3.2 and after
    # => [1, 2]
    ```

- [x] Constant assignment evaluation order for constants set on explicit
  objects has been made consistent with single attribute assignment
  evaluation order. With this code:

    ```ruby
    foo::BAR = baz
    ```

    `foo` is now called before `baz`. Similarly, for multiple assignments
    to constants,  left-to-right evaluation order is used. With this
    code:

    ```ruby
    foo1::BAR1, foo2::BAR2 = baz1, baz2
    ```

    The following evaluation order is now used:

    1. `foo1`
    2. `foo2`
    3. `baz1`
    4. `baz2`

    [[Bug #15928]]

- [x] "Find pattern" is no longer experimental.
  [[Feature #18585]]

- [ ] Methods taking a rest parameter (like `*args`) and wishing to delegate keyword
  arguments through `foo(*args)` must now be marked with `ruby2_keywords`
  (if not already the case). In other words, all methods wishing to delegate
  keyword arguments through `*args` must now be marked with `ruby2_keywords`,
  with no exception. This will make it easier to transition to other ways of
  delegation once a library can require Ruby 3+. Previously, the `ruby2_keywords`
  flag was kept if the receiving method took `*args`, but this was a bug and an
  inconsistency. A good technique to find the potentially-missing `ruby2_keywords`
  is to run the test suite, for where it fails find the last method which must
  receive keyword arguments, use `puts nil, caller, nil` there, and check each
  method/block on the call chain which must delegate keywords is correctly marked
  as `ruby2_keywords`. [[Bug #18625]] [[Bug #16466]]

    ```ruby
    def target(**kw)
    end

    # Accidentally worked without ruby2_keywords in Ruby 2.7-3.1, ruby2_keywords
    # needed in 3.2+. Just like (*args, **kwargs) or (...) would be needed on
    # both #foo and #bar when migrating away from ruby2_keywords.
    ruby2_keywords def bar(*args)
      target(*args)
    end

    ruby2_keywords def foo(*args)
      bar(*args)
    end

    foo(k: 1)
    ```

- [ ] `eval` and related methods are able to generate code coverage. Enabled using
  `Coverage.setup(:all)` or `Coverge.setup(eval: true)`. [[Feature #19008]]

- [x] `Coverage.supported?(mode)` enables detection of what coverage modes are
  supported. [[Feature #19026]]

## Core classes updates

Note: We're only listing outstanding class updates.

* Fiber

    - [x] Introduce Fiber.[] and Fiber.[]= for inheritable fiber storage.
      Introduce Fiber#storage and Fiber#storage= (experimental) for
      getting and resetting the current storage.  Introduce
      `Fiber.new(storage:)` for setting the storage when creating a
      fiber. [[Feature #19078]]

        Existing Thread and Fiber local variables can be tricky to use.
        Thread local variables are shared between all fibers, making it
        hard to isolate, while Fiber local variables can be hard to
        share.  It is often desirable to define unit of execution
        ("execution context") such that some state is shared between all
        fibers and threads created in that context.  This is what Fiber
        storage provides.

        ```ruby
        def log(message)
          puts "#{Fiber[:request_id]}: #{message}"
        end

        def handle_requests
          while request = read_request
            Fiber.schedule do
              Fiber[:request_id] = SecureRandom.uuid

              request.messages.each do |message|
                Fiber.schedule do
                  log("Handling #{message}") # Log includes inherited request_id.
                end
              end
            end
          end
        end
        ```

        You should generally consider Fiber storage for any state which
        you want to be shared implicitly between all fibers and threads
        created in a given context, e.g. a connection pool, a request
        id, a logger level, environment variables, configuration, etc.

* Fiber::Scheduler

    - [x] Introduce `Fiber::Scheduler#io_select` for non-blocking IO.select.
      [[Feature #19060]]

* IO

    - [ ] Introduce IO#timeout= and IO#timeout which can cause
      IO::TimeoutError to be raised if a blocking operation exceeds the
      specified timeout. [[Feature #18630]] #8662

        ```ruby
        STDIN.timeout = 1
        STDIN.read # => Blocking operation timed out! (IO::TimeoutError)
        ```

* UNIXSocket

    - [ ] Add support for UNIXSocket on Windows. Emulate anonymous sockets. Add
      support for File.socket? and File::Stat#socket? where possible.
      [[Feature #19135]]

* Class

    - [x] Class#attached_object, which returns the object for which
      the receiver is the singleton class. Raises TypeError if the
      receiver is not a singleton class.
      [[Feature #12084]]

        ```ruby
        class Foo; end

        Foo.singleton_class.attached_object        #=> Foo
        Foo.new.singleton_class.attached_object    #=> #<Foo:0x000000010491a370>
        Foo.attached_object                        #=> TypeError: `Foo' is not a singleton class
        nil.singleton_class.attached_object        #=> TypeError: `NilClass' is not a singleton class
        ```

* Data

    - [x] New core class to represent simple immutable value object. The class is
      similar to Struct and partially shares an implementation, but has more
      lean and strict API. [[Feature #16122]]

* Encoding

    - [x] Encoding#replicate has been deprecated and will be removed in 3.3. [[Feature #18949]]
    - [ ] The dummy `Encoding::UTF_16` and `Encoding::UTF_32` encodings no longer
      try to dynamically guess the endian based on a byte order mark.
      Use `Encoding::UTF_16BE`/`UTF_16LE` and `Encoding::UTF_32BE`/`UTF_32LE` instead.
      This change speeds up getting the encoding of a String. [[Feature #18949]]

* Enumerator

    - [x] Enumerator.product has been added.  Enumerator::Product is the implementation. [[Feature #18685]]

* Exception

    - [x] Exception#detailed_message has been added.
      The default error printer calls this method on the Exception object
      instead of #message. [[Feature #18564]]

* Hash

    - [x] Hash#shift now always returns nil if the hash is
      empty, instead of returning the default value or
      calling the default proc. [[Bug #16908]]

* Integer

    - [x] Integer#ceildiv has been added. [[Feature #18809]]

* Kernel

    - [ ] Kernel#binding raises RuntimeError if called from a non-Ruby frame
      (such as a method defined in C). [[Bug #18487]]

* MatchData

    - [x] MatchData#byteoffset has been added. [[Feature #13110]]
    - [x] MatchData#deconstruct has been added. [[Feature #18821]]
    - [x] MatchData#deconstruct_keys has been added. [[Feature #18821]]

* Module

    - [ ] Module.used_refinements has been added. [[Feature #14332]]
    - [x] Module#refinements has been added. [[Feature #12737]]
    - [x] Module#const_added has been added. [[Feature #17881]]
    - [x] Module#undefined_instance_methods has been added. [[Feature #12655]]

* Proc

    - [x] Proc#dup returns an instance of subclass. [[Bug #17545]]
    - [x] Proc#parameters now accepts lambda keyword. [[Feature #15357]]

* Process
    - [ ] Added `RLIMIT_NPTS` constant to FreeBSD platform

* Regexp

    - [x] Regexp.new now supports passing the regexp flags not only as an Integer,
      but also as a String.  Unknown flags raise ArgumentError.
      Otherwise, anything other than `true`, `false`, `nil` or Integer will be warned.
      [[Feature #18788]]

    - [x] Regexp.timeout= has been added. Also, Regexp.new new supports timeout keyword.
      See [[Feature #17837]]

* Refinement

    - [x] Refinement#refined_class has been added. [[Feature #12737]]

* RubyVM::AbstractSyntaxTree

    - [ ] Add `error_tolerant` option for `parse`, `parse_file` and `of`. [[Feature #19013]]
      With this option

        1. SyntaxError is suppressed
        2. AST is returned for invalid input
        3. `end` is complemented when a parser reachs to the end of input but `end` is insufficient
        4. `end` is treated as keyword based on indent

        ```ruby
        # Without error_tolerant option
        root = RubyVM::AbstractSyntaxTree.parse(<<~RUBY)
        def m
          a = 10
          if
        end
        RUBY
        # => <internal:ast>:33:in `parse': syntax error, unexpected `end' (SyntaxError)

        # With error_tolerant option
        root = RubyVM::AbstractSyntaxTree.parse(<<~RUBY, error_tolerant: true)
        def m
          a = 10
          if
        end
        RUBY
        p root # => #<RubyVM::AbstractSyntaxTree::Node:SCOPE@1:0-4:3>

        # `end` is treated as keyword based on indent
        root = RubyVM::AbstractSyntaxTree.parse(<<~RUBY, error_tolerant: true)
        module Z
          class Foo
            foo.
          end

          def bar
          end
        end
        RUBY
        p root.children[-1].children[-1].children[-1].children[-2..-1]
        # => [#<RubyVM::AbstractSyntaxTree::Node:CLASS@2:2-4:5>, #<RubyVM::AbstractSyntaxTree::Node:DEFN@6:2-7:5>]
        ```

    - [ ] Add `keep_tokens` option for `parse`, `parse_file` and `of`. Add `#tokens` and `#all_tokens`
      for RubyVM::AbstractSyntaxTree::Node [[Feature #19070]]

        ```ruby
        root = RubyVM::AbstractSyntaxTree.parse("x = 1 + 2", keep_tokens: true)
        root.tokens # => [[0, :tIDENTIFIER, "x", [1, 0, 1, 1]], [1, :tSP, " ", [1, 1, 1, 2]], ...]
        root.tokens.map{_1[2]}.join # => "x = 1 + 2"
        ```

* Set

    - [x] Set is now available as a built-in class without the need for `require "set"`. [[Feature #16989]]
      It is currently autoloaded via the Set constant or a call to Enumerable#to_set.

* Socket

    - [ ] Added the following constants for supported platforms.
        * `SO_INCOMING_CPU`
        * `SO_INCOMING_NAPI_ID`
        * `SO_RTABLE`
        * `SO_SETFIB`
        * `SO_USER_COOKIE`
        * `TCP_KEEPALIVE`
        * `TCP_CONNECTION_INFO`

* String

    - [x] String#byteindex and String#byterindex have been added. [[Feature #13110]]
    - [x] Update Unicode to Version 15.0.0 and Emoji Version 15.0. [[Feature #18639]]
      (also applies to Regexp)
    - [x] String#bytesplice has been added.  [[Feature #18598]]

* Struct

    - [x] A Struct class can also be initialized with keyword arguments
      without `keyword_init: true` on Struct.new [[Feature #16806]]

* Time

    - [x] Time#deconstruct_keys is added, allowing to use Time instances
      in pattern-matching expressions [[Feature #19071]]

* SyntaxError
    - [x] SyntaxError#path has been added.  [[Feature #19138]]

* TracePoint

    - [ ] TracePoint#binding now returns `nil` for `c_call`/`c_return` TracePoints.
      [[Bug #18487]]
    - [ ] TracePoint#enable `target_thread` keyword argument now defaults to the
      current thread if `target` and `target_line` keyword arguments are not
      passed. [[Bug #16889]]

## Stdlib updates

**Note:** Most of these updates are superseded by those in #8029.

* ERB

    - [ ] `-S` option is removed from `erb` command.

* FileUtils

    - [x] Add FileUtils.ln_sr method and `relative:` option to FileUtils.ln_s.
      [[Feature #18925]]

* SyntaxSuggest

    - [x] The feature of `syntax_suggest` formerly `dead_end` is integrated in Ruby.
      [[Feature #18159]]
    - [ ] Update once https://github.com/ruby/syntax_suggest/issues/215 is addressed.

*   The following default gems are updated.

    - [x] RubyGems 3.4.0.dev
    - [x] benchmark 0.2.1
    - [x] bigdecimal 3.1.3
    - [x] bundler 2.4.0.dev
    - [x] cgi 0.3.6
    - [x] date 3.3.0
    - [x] delegate 0.3.0
    - [x] did_you_mean 1.6.2
    - [x] digest 3.1.1
    - [x] drb 2.1.1
    - [x] erb 4.0.2
    - [x] error_highlight 0.5.1
    - [ ] etc 1.4.1
    - [ ] fcntl 1.0.2
    - [x] fiddle 1.1.1
    - [x] fileutils 1.7.0
    - [x] forwardable 1.3.3
    - [x] getoptlong 0.2.0
    - [x] io-console 0.5.11
    - [ ] io-nonblock 0.2.0
    - [x] io-wait 0.3.0.pre
    - [x] ipaddr 1.2.5
    - [x] irb 1.5.1
    - [x] json 2.6.2
    - [x] logger 1.5.2
    - [x] mutex_m 0.1.2
    - [x] net-http 0.3.1
    - [x] net-protocol 0.2.0
    - [x] nkf 0.1.2
    - [x] open-uri 0.3.0
    - [ ] openssl 3.1.0.pre
    - [x] optparse 0.3.0
    - [x] ostruct 0.5.5
    - [ ] pathname 0.2.1
    - [x] pp 0.4.0
    - [x] pstore 0.1.2
    - [x] psych 5.0.0
    - [x] racc 1.6.1
    - [x] rdoc 6.5.0
    - [x] reline 0.3.1
    - [x] resolv 0.2.2
    - [x] securerandom 0.2.1
    - [ ] set 1.0.3
    - [x] stringio 3.0.3
    - [x] syntax_suggest 1.0.1
    - [x] timeout 0.3.1
    - [ ] tmpdir 0.1.3
    - [x] tsort 0.1.1
    - [x] un 0.2.1
    - [x] uri 0.12.0
    - [ ] win32ole 1.8.9
    - [ ] zlib 3.0.0

*   The following bundled gems are updated.

    - [x] minitest 5.16.3
    - [x] power_assert 2.0.2
    - [x] test-unit 3.5.5
    - [x] net-ftp 0.2.0
    - [x] net-imap 0.3.1
    - [x] net-pop 0.1.2
    - [x] net-smtp 0.3.3
    - [ ] rbs 2.8.1
    - [ ] typeprof 0.21.3
    - [ ] debug 1.7.0

## Compatibility issues

Note: Excluding feature bug fixes.

### Removed constants

The following deprecated constants are removed.

- [x] `Fixnum` and `Bignum` [[Feature #12005]]
- [x] `Random::DEFAULT` [[Feature #17351]]
- [x] `Struct::Group`
- [x] `Struct::Passwd`

### Removed methods

The following deprecated methods are removed.

- [x] `Dir.exists?` [[Feature #17391]]
- [x] `File.exists?` [[Feature #17391]]
- [x] `Kernel#=~` [[Feature #15231]]
- [x] `Kernel#taint`, `Kernel#untaint`, `Kernel#tainted?`
  [[Feature #16131]]
- [x] `Kernel#trust`, `Kernel#untrust`, `Kernel#untrusted?`
  [[Feature #16131]]

[Feature #12005]: https://bugs.ruby-lang.org/issues/12005
[Feature #12084]: https://bugs.ruby-lang.org/issues/12084
[Feature #12655]: https://bugs.ruby-lang.org/issues/12655
[Feature #12737]: https://bugs.ruby-lang.org/issues/12737
[Feature #13110]: https://bugs.ruby-lang.org/issues/13110
[Feature #14332]: https://bugs.ruby-lang.org/issues/14332
[Feature #15231]: https://bugs.ruby-lang.org/issues/15231
[Feature #15357]: https://bugs.ruby-lang.org/issues/15357
[Bug #15928]:     https://bugs.ruby-lang.org/issues/15928
[Feature #16122]: https://bugs.ruby-lang.org/issues/16122
[Feature #16131]: https://bugs.ruby-lang.org/issues/16131
[Bug #16466]:     https://bugs.ruby-lang.org/issues/16466
[Feature #16806]: https://bugs.ruby-lang.org/issues/16806
[Bug #16889]:     https://bugs.ruby-lang.org/issues/16889
[Bug #16908]:     https://bugs.ruby-lang.org/issues/16908
[Feature #16989]: https://bugs.ruby-lang.org/issues/16989
[Feature #17351]: https://bugs.ruby-lang.org/issues/17351
[Feature #17391]: https://bugs.ruby-lang.org/issues/17391
[Bug #17545]:     https://bugs.ruby-lang.org/issues/17545
[Feature #17837]: https://bugs.ruby-lang.org/issues/17837
[Feature #17881]: https://bugs.ruby-lang.org/issues/17881
[Feature #18159]: https://bugs.ruby-lang.org/issues/18159
[Feature #18351]: https://bugs.ruby-lang.org/issues/18351
[Feature #18481]: https://bugs.ruby-lang.org/issues/18481
[Bug #18487]:     https://bugs.ruby-lang.org/issues/18487
[Feature #18564]: https://bugs.ruby-lang.org/issues/18564
[Feature #18571]: https://bugs.ruby-lang.org/issues/18571
[Feature #18585]: https://bugs.ruby-lang.org/issues/18585
[Feature #18589]: https://bugs.ruby-lang.org/issues/18589
[Feature #18598]: https://bugs.ruby-lang.org/issues/18598
[Bug #18625]:     https://bugs.ruby-lang.org/issues/18625
[Feature #18630]: https://bugs.ruby-lang.org/issues/18630
[Bug #18633]:     https://bugs.ruby-lang.org/issues/18633
[Feature #18639]: https://bugs.ruby-lang.org/issues/18639
[Feature #18685]: https://bugs.ruby-lang.org/issues/18685
[Feature #18776]: https://bugs.ruby-lang.org/issues/18776
[Bug #18782]:     https://bugs.ruby-lang.org/issues/18782
[Feature #18788]: https://bugs.ruby-lang.org/issues/18788
[Feature #18809]: https://bugs.ruby-lang.org/issues/18809
[Feature #18821]: https://bugs.ruby-lang.org/issues/18821
[Feature #18824]: https://bugs.ruby-lang.org/issues/18824
[Feature #18925]: https://bugs.ruby-lang.org/issues/18925
[Feature #18949]: https://bugs.ruby-lang.org/issues/18949
[Feature #18968]: https://bugs.ruby-lang.org/issues/18968
[Feature #19008]: https://bugs.ruby-lang.org/issues/19008
[Feature #19013]: https://bugs.ruby-lang.org/issues/19013
[Feature #19026]: https://bugs.ruby-lang.org/issues/19026
[Feature #19060]: https://bugs.ruby-lang.org/issues/19060
[Feature #19070]: https://bugs.ruby-lang.org/issues/19070
[Feature #19071]: https://bugs.ruby-lang.org/issues/19071
[Feature #19078]: https://bugs.ruby-lang.org/issues/19078
[Bug #19100]:     https://bugs.ruby-lang.org/issues/19100
[Feature #19135]: https://bugs.ruby-lang.org/issues/19135
[Feature #19138]: https://bugs.ruby-lang.org/issues/19138

**Comment by k77ch7** [comment]
@headius Can I make some PRs for 3.2 features against the master branch?
9.4 branch does not exist yet, though.

**Comment by enebo** [comment]
@k77ch7 I just made a ruby-3.2 branch.  You can make a PR against that branch (also if you want we still have 3.1 failures in wip too).

After a point release or 2 we will create a maintenance branch for jruby 9.4.x and ruby-3.2 will become master but not yet.

**Comment by edipofederle** [comment]
Hi,

Someone with credentials can tick the "Integer#ceildiv has been added. [[Feature #18809](https://bugs.ruby-lang.org/issues/18809)]" since it was merged here: https://github.com/jruby/jruby/pull/7646

Thanks

**Comment by headius** [comment]
Thanks for the heads up, @edipofederle!

**Comment by thbar** [comment]
TIL this one is a blocker for [rails 8](https://rubygems.org/gems/rails/versions/8.0.1) or event activesupport upgrades.

(no pressure, just sharing a data point & I know this is hard work :-))

**Comment by enebo** [comment]
@thbar yeah this is coming for JRuby 10 since Jruby 9 was 3.1.  We hope this quarter to have it out.

**Comment by thbar** [comment]
> @thbar yeah this is coming for JRuby 10 since Jruby 9 was 3.1. We hope this quarter to have it out.

Thank you for the confirmation! & again, no pressure, & happy to provide test suite results later if this helps.

**Comment by headius** [comment]
Checklist updated today.
