### ISSUE TITLE
Ruby 3.3 support

### ISSUE THREAD

**Issue by headius** [jruby/jruby#8029]
# NEWS for Ruby 3.3.0

This document is a list of user-visible feature changes
since the **3.2.0** (see #7517 for 3.2 support) release, except for bug fixes.

Note that each entry is kept to a minimum, see links for details.

## Command line options

* [x] A new `performance` warning category was introduced.
  They are not displayed by default even in verbose mode.
  Turn them on with `-W:performance` or `Warning[:performance] = true`. [[Feature #19538]]

* [ ] A new `RUBY_CRASH_REPORT` environment variable was introduced to allow
  redirecting Ruby crash reports to a file or sub command. See the `BUG REPORT ENVIRONMENT`
  section of the ruby manpage for further details. [[Feature #19790]]

## Core classes updates

Note: We're only listing outstanding class updates.

* Array

    * [x] Array#pack now raises ArgumentError for unknown directives. [[Bug #19150]]

* Dir

    * [ ] Dir.for_fd added for returning a Dir object for the directory specified
      by the provided directory file descriptor. [[Feature #19347]]
    * [ ] Dir.fchdir added for changing the directory to the directory specified
      by the provided directory file descriptor. [[Feature #19347]]
    * [x] Dir#chdir added for changing the directory to the directory specified by
      the provided `Dir` object. [[Feature #19347]]

* MatchData

    * [x] MatchData#named_captures now accepts optional `symbolize_names`
      keyword. [[Feature #19591]]

* Module

    * [x] Module#set_temporary_name added for setting a temporary name for a
      module. [[Feature #19521]]

* ObjectSpace::WeakKeyMap

    * [x] New core class to build collections with weak references.
      The class use equality semantic to lookup keys like a regular hash,
      but it doesn't hold strong references on the keys. [[Feature #18498]]

* ObjectSpace::WeakMap

    * [x] `ObjectSpace::WeakMap#delete` was added to eagerly clear weak map
      entries. [[Feature #19561]]

* Proc
    * [x] Now Proc#dup and Proc#clone call `#initialize_dup` and `#initialize_clone`
      hooks respectively.  [[Feature #19362]]

* Process

    * [x] New `Process.warmup` method that notify the Ruby virtual machine that the boot sequence is finished,
      and that now is a good time to optimize the application. This is useful
      for long-running applications. The actual optimizations performed are entirely
      implementation-specific and may change in the future without notice. [[Feature #18885]]

* Process::Status

    * [x] Process::Status#& and Process::Status#>> are deprecated. [[Bug #19868]]

* Queue

    * [x] Queue#freeze now raises TypeError. [[Bug #17146]]

* Range

    * [x] Range#reverse_each can now process beginless ranges with an Integer endpoint. [[Feature #18515]]
    * [x] Range#reverse_each now raises TypeError for endless ranges. [[Feature #18551]]

* Refinement

    * [x] Add Refinement#target as an alternative of Refinement#refined_class.
      Refinement#refined_class is deprecated and will be removed in Ruby
      3.4.  [[Feature #19714]]

* SizedQueue

    * [x] SizedQueue#freeze now raises TypeError. [[Bug #17146]]

* String

    * [x] String#unpack now raises ArgumentError for unknown directives. [[Bug #19150]]
    * [x] String#bytesplice now accepts new arguments index/length or range of the
      source string to be copied.  [[Feature #19314]]

* TracePoint

    * [x] TracePoint supports `rescue` event. When the raised exception was rescued,
      the TracePoint will fire the hook. `rescue` event only supports Ruby-level
      `rescue`. [[Feature #19572]] (#7788)

## Stdlib updates

* [x] RubyGems and Bundler warn if users require gem that is scheduled to become the bundled gems
  in the future version of Ruby. [[Feature #19351]] [[Feature #19776]] [[Feature #19843]]

  Targeted libraries are:
    * abbrev
    * base64
    * bigdecimal
    * csv
    * drb
    * getoptlong
    * mutex_m
    * nkf
    * observer
    * racc
    * resolv-replace
    * rinda
    * syslog

* [ ] Socket#recv and Socket#recv_nonblock returns `nil` instead of an empty string on closed
  connections. Socket#recvmsg and Socket#recvmsg_nonblock returns `nil` instead of an empty packet on closed
  connections. [[Bug #19012]]

* [x] Random::Formatter#alphanumeric is extended to accept optional `chars`
  keyword argument. [[Feature #18183]]

The following default gem is added.

* [ ] prism 0.18.0

The following default gems are updated.

* [x] RubyGems 3.5.0.dev
* [x] base64 0.2.0
* [x] benchmark 0.3.0
* [x] bigdecimal 3.1.5 (stubbed for JRuby)
* [x] bundler 2.5.0.dev
* [x] cgi 0.4.0
* [x] csv 3.2.8
* [ ] date 3.3.4 (partially updated; stub JRuby gem)
* [x] delegate 0.3.1
* [x] drb 2.2.0
* [x] english 0.8.0
* [x] erb 4.0.3 (4.0.4 now, working through getting them to skip the ext on JRuby: https://github.com/ruby/erb/issues/52
* [ ] etc 1.4.3.dev.1 (no JRuby gem)
* [ ] fcntl 1.1.0 (no JRuby gem)
* [x] fiddle 1.1.2
* [x] fileutils 1.7.2
* [x] find 0.2.0
* [x] getoptlong 0.2.1
* [x] io-console 0.6.1.dev.1
* [x] irb 1.10.0
* [x] json 2.7.0
* [x] logger 1.6.0
* [x] mutex_m 0.2.0
* [x] net-http 0.4.0
* [x] net-protocol 0.2.2
* [x] nkf 0.1.3 (no JRuby gem)
* [x] observer 0.1.2
* [x] open-uri 0.4.0
* [x] open3 0.2.0
* [ ] openssl 3.2.0 (no JRuby gem)
* [x] optparse 0.4.0
* [x] ostruct 0.6.0
* [ ] pathname 0.3.0 (no JRuby gem)
* [x] pp 0.5.0
* [x] prettyprint 0.2.0
* [x] pstore 0.1.3
* [x] psych 5.1.1.1
* [x] rdoc 6.6.0
* [x] reline 0.4.0
* [x] rinda 0.2.0
* [x] securerandom 0.3.0
* [x] shellwords 0.2.0
* [x] singleton 0.2.0
* [x] stringio 3.1.1
* [x] strscan 3.0.8
* [x] syntax_suggest 1.1.0
* [x] tempfile 0.2.0
* [x] time 0.3.0
* [x] timeout 0.4.1
* [ ] tmpdir 0.2.0 (no JRuby gem)
* [x] tsort 0.2.0
* [x] un 0.3.0
* [x] uri 0.13.0
* [x] weakref 0.1.3
* [ ] win32ole 1.8.10 (no JRuby gem)
* [x] yaml 0.3.0
* [ ] zlib 3.1.0 (no JRuby gem)

The following bundled gem is promoted from default gems.

* [x] racc 1.7.3

The following bundled gems are updated.

* [x] minitest 5.20.0
* [x] rake 13.1.0
* [x] test-unit 3.6.1
* [x] rexml 3.2.6
* [x] rss 0.3.0
* [x] net-imap 0.4.7
* [x] net-smtp 0.4.0
* [ ] rbs 3.3.2 (no JRuby gem)
* [ ] typeprof 0.21.8 (no JRuby gem)
* [ ] debug 1.8.0 (no JRuby gem)

See GitHub releases like [Logger](https://github.com/ruby/logger/releases) or
changelog for details of the default gems or bundled gems.

## Compatibility issues

* [x] Subprocess creation/forking via the following file open methods is deprecated. [[Feature #19630]]
    * Kernel#open
    * URI.open
    * IO.binread
    * IO.foreach
    * IO.readlines
    * IO.read
    * IO.write

* [x] When given a non-lambda, non-literal block, Kernel#lambda with now raises
  ArgumentError instead of returning it unmodified. These usages have been
  issuing warnings under the `Warning[:deprecated]` category since Ruby 3.0.0.
  [[Feature #19777]]

* [ ] The `RUBY_GC_HEAP_INIT_SLOTS` environment variable has been deprecated and
  removed. Environment variables `RUBY_GC_HEAP_%d_INIT_SLOTS` should be
  used instead.  [[Feature #19785]]

## Stdlib compatibility issues

* [x] `racc` is promoted to bundled gems.
    * You need to add `racc` to your `Gemfile` if you use `racc` under bundler environment.
* [x] `ext/readline` is retired
    * We have `reline` that is pure Ruby implementation compatible with `ext/readline` API. We rely on `reline` in the future. If you need to use `ext/readline`, you can install `ext/readline` via rubygems.org with `gem install readline-ext`.
    * We no longer need to install libraries like `libreadline` or `libedit`.
    * JRuby: Similar work will need to happen to unbundle the jruby-readline library. See https://github.com/jruby/jruby/issues/8066.

## Implementation improvements

* [ ] `defined?(@ivar)` is optimized with Object Shapes.
* [ ] Name resolution such as `Socket.getaddrinfo` can now be interrupted. [[Feature #19965]]

## Undocumented:

* [x] New NameError handling of #message (ruby/ruby#6950)

[Bug #17146]:     https://bugs.ruby-lang.org/issues/17146
[Feature #18183]: https://bugs.ruby-lang.org/issues/18183
[Feature #18498]: https://bugs.ruby-lang.org/issues/18498
[Feature #18515]: https://bugs.ruby-lang.org/issues/18515
[Feature #18551]: https://bugs.ruby-lang.org/issues/18551
[Feature #18885]: https://bugs.ruby-lang.org/issues/18885
[Bug #19012]:     https://bugs.ruby-lang.org/issues/19012
[Bug #19150]:     https://bugs.ruby-lang.org/issues/19150
[Feature #19314]: https://bugs.ruby-lang.org/issues/19314
[Feature #19347]: https://bugs.ruby-lang.org/issues/19347
[Feature #19351]: https://bugs.ruby-lang.org/issues/19351
[Feature #19362]: https://bugs.ruby-lang.org/issues/19362
[Feature #19521]: https://bugs.ruby-lang.org/issues/19521
[Feature #19538]: https://bugs.ruby-lang.org/issues/19538
[Feature #19561]: https://bugs.ruby-lang.org/issues/19561
[Feature #19571]: https://bugs.ruby-lang.org/issues/19571
[Feature #19572]: https://bugs.ruby-lang.org/issues/19572
[Feature #19591]: https://bugs.ruby-lang.org/issues/19591
[Feature #19630]: https://bugs.ruby-lang.org/issues/19630
[Feature #19678]: https://bugs.ruby-lang.org/issues/19678
[Feature #19714]: https://bugs.ruby-lang.org/issues/19714
[Feature #19776]: https://bugs.ruby-lang.org/issues/19776
[Feature #19777]: https://bugs.ruby-lang.org/issues/19777
[Feature #19785]: https://bugs.ruby-lang.org/issues/19785
[Feature #19790]: https://bugs.ruby-lang.org/issues/19790
[Feature #19842]: https://bugs.ruby-lang.org/issues/19842
[Feature #19843]: https://bugs.ruby-lang.org/issues/19843
[Bug #19868]:     https://bugs.ruby-lang.org/issues/19868
[Feature #19965]: https://bugs.ruby-lang.org/issues/19965

**Comment by headius** [comment]
* Undocumented:

* [ ] New NameError handling of #message (ruby/ruby#6950)

**Comment by headius** [comment]
Checklist updated today.
