### ISSUE TITLE
Missing TracePoint features

### ISSUE THREAD

**Issue by headius** [jruby/jruby#8098]
A number of TracePoint features have never been implemented. This is a catch-all bug for those features.

From Ruby 2.6:

- [ ] “script_compiled” event is supported. [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [ ] TracePoint#parameters [Feature #14694](https://bugs.ruby-lang.org/issues/14694)
- [ ] TracePoint#instruction_sequence [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [ ] TracePoint#eval_script [Feature #15287](https://bugs.ruby-lang.org/issues/15287)
- [ ] TracePoint#enable accepts new keywords “target:” and “target_line:”.[Feature #15289](https://bugs.ruby-lang.org/issues/15289)
